### ISSUE TITLE
String concatenation operator not supported by AMOS

### ISSUE THREAD

**Issue by mudrd8mz** [h5p/h5p-moodle-plugin#100]
Unfortunately, the Moodle translation system AMOS does not yet support the strings concatenation operator when parsing plugins' string files. Therefore it could not register strings of your plugin yet. Please check the strings at the end of the strings file (starting with the string welcomegettingstarted) and remove the concatenation operator there.

https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by icc** [comment]
Thank you for reporting!
