### ISSUE TITLE
capability mod/hvp:addinstance

### ISSUE THREAD

**Issue by s-cenni** [h5p/h5p-moodle-plugin#101]
I installed the plugin and, in editing mode, I got this error.

```
The module hvp does not define the standard capability mod/hvp:addinstance
line 2303 of /course/lib.php: call to debugging()
line 1271 of /course/lib.php: call to course_allowed_module()
line 439 of /course/renderer.php: call to get_module_metadata()
line 857 of /course/format/renderer.php: call to core_course_renderer->course_section_add_cm_control()
line 56 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
line 280 of /course/view.php: call to require()
```

I fixed changing the version number like suggested here (http://stackoverflow.com/questions/16255206/moodle-the-module-mymodule-does-not-define-the-standard-capability)

**Comment by icc** [comment]
This appears to be working now. Please reopen if you're still experiencing issues with this.

**Comment by CinecaElearning** [comment]
Hello,
we just installed release 1.4, version 2017060600 on a 3.1.6 (Build: 20170508) Moodle.

The module hvp does not define the standard capability mod/hvp:addinstance
line 2422 of /course/lib.php: call to debugging()
line 435 of /course/modlib.php: call to course_allowed_module()
line 63 of /course/modedit.php: call to can_add_moduleinfo()

Looking forwart to hearing from you,
Cineca Elearning Group

**Comment by icc** [comment]
Hi, 
Where did you download the plugin? 
If you check your mod/hvp/db/access.php file the first capability defined should be 'mod/hvp:addinstance'

**Comment by leac** [comment]
Hi

I'm getting the same error, in my Moodle 3.5 instance.
I cloned the repository from its stable branch a few days ago.
I do see capability 'mod/hvp:addinstance' defined  in mod/hvp/db/access.php, line 51. 

What could the problem be?
Thank you
