### ISSUE TITLE
Assets don't load when setup in guest-access course

### ISSUE THREAD

**Issue by OdyX** [h5p/h5p-moodle-plugin#106]
When setting up an h5p activity in a course with "Guest Access" enabled, the h5p will fail to load because of the following missing permissions:
- `mod/hvp:getcachedassets`
- `mod/hvp:getcontent`

These permissions should be granted to the 'guest' user role.

**Comment by AlexWatterson** [comment]
Is this likely to be fixed? I noticed its only images which appear to not work, things like drag and drop and video do work.
Thanks

**Comment by thomasmars** [comment]
This should be possible to configure for each role separately. Feel free to reopen the issue if this is wrong.
