### ISSUE TITLE
Include libraries into activity backup

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#107]
Need to figure out how to either:
- Include used libraries into the backup
- Implement a feature that checks the installed libraries and tells the user to install the missing ones before continuing the restore

Related discussion at Moodle community forums: https://moodle.org/mod/forum/discuss.php?d=329789

**Comment by thomasmars** [comment]
I think this has been implemented. Feel free to reopen if I'm incorrect
