### ISSUE TITLE
Add hook/event to alter filtered parameters

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#11]
Makes it easier for other plugins to alter or modify the parameters before they are printed.
Should run after `$core->filterParameters()`

[WordPress plugin's h5p_alter_filtered_parameters](https://github.com/h5p/h5p-wordpress-plugin/blob/master/public/class-h5p-plugin.php#L657)

**Comment by thomasmars** [comment]
Added in https://github.com/h5p/h5p-moodle-plugin/commit/ff8adcc3d0b64f0b7ac4c15f8fee24f98a512a9f
