### ISSUE TITLE
Custom CSS provided by configuration/themes

### ISSUE THREAD

**Issue by LukeCarrier** [h5p/h5p-moodle-plugin#110]
One of our requirements is the ability to customise the CSS used within H5P content, regardless of embed type. This poses a problem at the moment, as customisations made within the theme are only applied to activities that support the `<div>` embed type.

Unfortunately it's not possible to extend Moodle's theme configuration system to do this. I first thought we could simply set `$THEME->mod_hvp_sheets` in a theme's `config.php` then, in H5P, access `$PAGE->theme->mod_hvp_sheets`. This isn't possible, because `$THEME` is really just a `stdClass`.

The tidiest way I can see to do this is to move `hvp_get_core_assets()` into a [renderer method](https://docs.moodle.org/dev/Output_renderers) or [other callback](https://github.com/moodle/moodle/blob/9d8a3055c064d2177ac6e939f3d17392f10be699/lib/moodlelib.php#L7418-L7441), allowing themes to override these methods as appropriate.

Would a PR be accepted for either of these approaches? I'm definitely open to suggestions.

**Comment by mwilday** [comment]
I cannot speak specifically into the method on how this would be accomplished, but it would be fantastic to have this option. 

I'd imagine, in some hosted instances, that settings within the plugin would hook into the themes in some way. I could imagine a text-input box for adding custom CSS specifically in the settings panel for the plugin. Or some measure of adding a to the themes with the installation of the plugin (though I don't know the possibility of that with a Moodle Plugin). Our Moodle vendor -- moodlerooms --
does not allow access to the code base so adding any custom themes on our end is a no-go. 

I'd also  suggest implementing the methods found here: https://h5p.org/documentation/for-developers/visual-changes -- there is some information on adding this to moodle that might be helpful in the implementation.  Something from here might be useful too: https://h5p.org/change-color-of-the-editor
