### ISSUE TITLE
Fast forward / Rewind button 

### ISSUE THREAD

**Issue by mlclmv** [h5p/h5p-moodle-plugin#111]
Was wondering if I could get any help on how to add +- 5s/ 10s buttons to the video player. This plugin is amazing but I think that this is an important feature and I would like to implement it. But I have no idea how since I'm a novice.

Thanks!

**Comment by thomasmars** [comment]
Please post any Video specific issues to the h5p-video repository: https://github.com/h5p/h5p-video
