### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by Mihailoff** [h5p/h5p-moodle-plugin#113]
Have you thought about using composer to manage dependencies like "library" and "editor" instead of git submodules?

https://getcomposer.org/

**Comment by thomasmars** [comment]
You would have to include the vendor folder then ? There may be some merit to doing it this way if you were using more dependencies/composer packages. Do you have any examples of other modules doing it with composer ?
I'm closing this for now, feel free to reopen it with some more info on the benefits of using composer, and successfull examples of other Moodle modules that is using it.
