### ISSUE TITLE
Spanish Language

### ISSUE THREAD

**Issue by opinco** [h5p/h5p-moodle-plugin#116]
Hi, I'm glad to contribute a Spanish lang package for Moodle. But, as a non-programmer, I found that every extended character like é, ñ, Á etc. appears as � in my Moodle installation. How do I convert this characters? Find attached the lang file.
[hvp-lang-es.txt](https://github.com/h5p/h5p-moodle-plugin/files/537611/hvp-lang-es.txt)

**Comment by ivakh** [comment]
Maybe it is the character encoding of your server

**Comment by opinco** [comment]
I don't think so, as every other language pack is working well. Anyway, this seems an old issue that is resolving somewhere else.Thank you Iván Osvaldo Pinco 


      De: Iván Muñoz <notifications@github.com>
 Para: h5p/h5p-moodle-plugin <h5p-moodle-plugin@noreply.github.com> 
CC: opinco <osvaldo.pinco@yahoo.com>; Author <author@noreply.github.com>
 Enviado: Jueves, 16 de febrero, 2017 10:23:05
 Asunto: Re: [h5p/h5p-moodle-plugin] Spanish Language (#116)
   
Maybe it is the character encoding of your server—

**Comment by timothyylim** [comment]
@opinco , that seems a bit strange. Let me know if you do not manage to solve it.

**Comment by icc** [comment]
The file isn't valid UTF-8. I'm guessing that ISO-8859 is used but the server tells the browser that it's UTF-8

**Comment by opinco** [comment]
Thanks for your comments. I was using Notepad to edit the file. I'm using a proper text editor now, and it looks ok. But I couldn't test it in my install. Would you please check it?
I took the time to finish the translation, even the more technical strings at the end, which I left untranslated before. Please find file attached
[hvp-lang-es.txt](https://github.com/h5p/h5p-moodle-plugin/files/783281/hvp-lang-es.txt)

**Comment by timothyylim** [comment]
@opinco , looks like the symbols are still showing up. Have you tried writing it with the Atom text editor?

**Comment by opinco** [comment]
[hvp_lang_es.txt](https://github.com/h5p/h5p-moodle-plugin/files/787434/hvp_lang_es.txt)
Thank you Timothy. I opened the file and corrected it in Atom. I hope this is the good one.
Cheers!

**Comment by timothyylim** [comment]
@opinco , I'll merge it in this week and it should be part of the next release :)

**Comment by lagartojf** [comment]
Hi everybody, can you tell me how to configure the spanish lang for H5P on Moodle so I can read it in spanish. I made my translation file, didn't see before your file, sorry, but I don't know how to configure it to use it. Thanks for the help!

**Comment by timothyylim** [comment]
Hi @lagartojf , you can either wait for the next release and by then we should have @opinco 's spanish translations ready or you can manually navigate to your lang directory and create a new folder for Spanish just like the other languages:

https://github.com/h5p/h5p-moodle-plugin/tree/master/lang

Let me know if you need any help :)

**Comment by opinco** [comment]
Hello
sorry to bother you again. 
I was able to create a "mod/hvp/lang/es" directory in my Moodle installation, and it went OK, regarding the administrative part of the module. I hope you can include this into the next release.
But what I was trying to achieve was different from this. I want to translate every word that appears in the user interfase to Spanish.  For example this screen
![captura de pantalla 2017-09-12 12 01 51](https://user-images.githubusercontent.com/22356902/30333036-50dbf4d8-97b2-11e7-8618-78cfddf05eec.png)

Would you please tell me where to find this strings, and how to contribute to the translation?
Thank you in advance

**Comment by timothyylim** [comment]
Sorry for the late reply @opinco. If you make a pull request with your new language file, I'll happily merge it in and make sure it's part of the next release. 

For the final part you will have to translate the content types themselves:

https://github.com/h5p/h5p-single-choice-set/blob/master/language/es.json
