### ISSUE TITLE
Cannot translate all string in Moodle language pack

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#117]
Hello,

I'm trying to translate Moodles Interactive Video -activity to my own language (Finnish) 

I cannot seem to find all the strings from Moodle language pack it's like they are missing f.ex;

<hr>

**All the text inside all the content types for example interactive video;**

![intvideo](https://cloud.githubusercontent.com/assets/15193418/19592615/4136f498-9785-11e6-9f80-2c6e465d7116.PNG)

<hr>

**The list of the content types;**
![aineistot](https://cloud.githubusercontent.com/assets/15193418/19592618/47e6fea0-9785-11e6-885c-55db6c4d43ae.png)

<hr>

**Confirm message when changing content type on the fly**
![confirm](https://cloud.githubusercontent.com/assets/15193418/19592627/4e0b9b24-9785-11e6-93dc-bc7c235ac580.PNG)

**Comment by juho-jaakkola** [comment]
Translations of each individual content type can be found from their own repositories. E.g. interactive video is here: https://github.com/h5p/h5p-interactive-video
