### ISSUE TITLE
Can't override with theme

### ISSUE THREAD

**Issue by atrnoble** [h5p/h5p-moodle-plugin#119]
As the module does not make use of renderers it makes it difficult to override the display of the module to fit in with a theme.

I am currently doing a bootstrap 3 theme for a client where they require the available video space to be smaller and place the title and info sections on the right in a smaller box. To do it currently this requires an edit of the incourse.php layout file just for H5P where elements of $OUTPUT->main_content are hidden with css and then grabbed from the database to be rendered again elsewhere. So a doable task but a bit of a pain and a little untidy.

Are there are plans to make H5P more themeable soon?

**Comment by thomasmars** [comment]
Was added in https://github.com/h5p/h5p-moodle-plugin/commit/f54a7c77fdc82880e3e83b987b02c6f445e44144.
Tutorials can be found at https://h5p.org/moodle-customization
