### ISSUE TITLE
Add hook/event to alter scripts and styles

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#12]
Makes it easier for other plugins to alter or modify the scripts and styles that are loaded.
Should run after `$core->getDependenciesFiles()`

[WordPress plugin's alter_assets()](https://github.com/h5p/h5p-wordpress-plugin/blob/master/public/class-h5p-plugin.php#L757)

**Comment by thomasmars** [comment]
Fixed in #133 and https://github.com/h5p/h5p-moodle-plugin/commit/b0f29dc0fc4930a28291dfab1a99cf6960f1bba6
