### ISSUE TITLE
h5p produces garbage and html tags while initializing phpunit testing

### ISSUE THREAD

**Issue by ewallah** [h5p/h5p-moodle-plugin#122]
Installing a plugin should not produce output. Moodle can also be managed from the command line, and then the html tags are only generating confusion. (Imagine you have 88 plugins installed and every plugin generates a "Welcome to the world of ..." )

To reproduce: 
/usr/bin/php admin/tool/phpunit/cli/init.php
Initialising Moodle PHPUnit test environment...
...
-->System
++ Success ++
-->mod_hvp
^[[A<3>Welcome to the world of H5P!</3><>To get started with H5P and Moodle take a look at our <>tutorial</> and check out the <>example content</> at H5P.org for inspiration.<>The most popuplar content types have been installed for your convenience!</><>We hope you will enjoy H5P and get engaged in our growing community through our <> and chat room <>H5P at Gitter</></><>If you have any feedback, don't hesitate to <>contact us</>. We take feedback very seriously and are dedicated to making H5P better every day!</>!! Added 88 new H5P libraries. !!
++ Success ++
-->mod_

**Comment by icc** [comment]
Perhaps we could move this to the upgradesettings.php page that is displayed after plugin activation?
Or at least, disable it or remove the HTML for CLI tools.

What do you think @thomasmars?

**Comment by thomasmars** [comment]
I think the message is valuable in itself, so it should be kept. I suppose moving it to upgradesettings.php is the cleanest solution if this is easy, since this would show every time it is installed anyway.

**Comment by ewallah** [comment]
Any idea of a fix?  I mentioned this problem more than 6 months ago and LOL with the phrase "We take feedback very seriously"

The whole idea of a Moodle plugin is expanding the possibilities of the software.  This h5p module is limiting at least 3 other aspects of Moodle :  dbtransfer - phpunit - behat testing.  Perhaps it is time to start mentioning these beta phase problems on the user fora?
