### ISSUE TITLE
upgrading to rc4 doesn't prompt library upgrade

### ISSUE THREAD

**Issue by dustinbrisebois** [h5p/h5p-moodle-plugin#123]
Some legacy libraries (H5PEditor.Duration for instance) maintained at version 1.0.6 after upgrading to rc4. Received upgrade warnings and was getting an error related to unable to upgrade library due to a minor version issue. To resolve had to uninstall / reinstall hvp from Moodle (3.x)

**Comment by dustinbrisebois** [comment]
Issue also exists in rc-5 where the only way to update libraries appears to uninstall/reinstall the plugin

**Comment by thomasmars** [comment]
I'm closing this issue. Please reopen if this is still an issue in the latest version of H5P.
