### ISSUE TITLE
Grade and completion records shouldn't be removed when editing activities

### ISSUE THREAD

**Issue by LukeCarrier** [h5p/h5p-moodle-plugin#130]
The way H5P processes changes to activities at the moment means that it removes all existing grade (and, by extension, completion) records for users. Whilst this may be appropriate if the editor is changing the activity's scope, it is too destructive where the editor is simply correcting a typo or making a simple copy change.

Moodle's quiz activity prevents users from making changes that'd invalidate the grades (e.g. changing the number of questions a user might be asked) until existing quiz attempts are removed, but still allows changes to the content of individual questions. Could the H5P editor be extended to do this, or would it be possible to otherwise indicate that "this change is a minor edit and should not trigger removal of grade outcomes"?

**Comment by falcon-git** [comment]
Would it be sufficient to just not delete those datas at all? In a future version we'll have answering reports as well that will show what the user answered and the question he answered.

**Comment by thomasmars** [comment]
Thanks for reporting this. It has been fixed in https://github.com/h5p/h5p-moodle-plugin/commit/1ee82d1da2ef240a757f68bf53651d0e7406baba by never resetting scores when updating an H5P. The change will be part of the next release if it survives the review process.
