### ISSUE TITLE
Unable to get any modules to display

### ISSUE THREAD

**Issue by patriclougheed** [h5p/h5p-moodle-plugin#132]
I have a Moodle 3.1 instance running in a PHP 5.6/Apache 2.4/Postgres config and none of the modules display after setting them up. I have quite a few activities installed and this is the only one giving me trouble. I have a similar install on another server and it all works fine and cannot figure out what I am missing.

Failed to load resource: the server responded with a status of 404 (Not Found) 
pluginfile.php/1/mod_hvp/cachedassets/d89356d83dfc81f47196e08b8e1f5f00ca211dcc.js 

Failed to load resource: the server responded with a status of 404 (Not Found)
 h5p.js?ver=2017010900:840 

Unable to find constructor for: H5P.TwitterUserFeed 1.0
H5P.error @ h5p.js?ver=2017010900:840
h5p.js?ver=2017010900:1718 

Uncaught TypeError: Cannot read property 'on' of undefined
    
at Object.H5P.on (h5p.js?ver=2017010900:1718)
    
at HTMLDivElement.<anonymous> (h5p.js?ver=2017010900:185)
    
at Function.each (jquery.js?ver=2017010900:2)
    
at init.each (jquery.js?ver=2017010900:2)
    
at Object.H5P.init (h5p.js?ver=2017010900:92)
    
at HTMLDocument.<anonymous> (h5p.js?ver=2017010900:2002)
    
at c (jquery.js?ver=2017010900:2)
    
at Object.fireWith [as resolveWith] (jquery.js?ver=2017010900:2)
    
at Function.ready (jquery.js?ver=2017010900:2)
    
at HTMLDocument.H (jquery.js?ver=2017010900:2) pluginfile.php/1/mod_hvp/cachedassets/d89356d83dfc81f47196e08b8e1f5f00ca211dcc.css 

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by icc** [comment]
I'm sorry to hear that you're having issues. It appears to be some files missing – it could have something to do with permissions or a problem when generating the files. Does the editor work properly when creating a new 'Interactive Content' activity?

You could try adding the following to your config.php temporarily to see if you get any more information or error messages:
```
@error_reporting(E_ALL | E_STRICT);   // NOT FOR PRODUCTION SERVERS!
@ini_set('display_errors', '1');         // NOT FOR PRODUCTION SERVERS!
$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
$CFG->debugdisplay = 1;              // NOT FOR PRODUCTION SERVERS!

$CFG->mod_hvp_dev = 1;
//$CFG->mod_hvp_aggregate_assets = 0;
```
(after the database stuff but before require setup.php) 

Do your web server's error_log file say anything?
Is the site a copy of the site that's working or is it a different site entirely?

**Comment by patriclougheed** [comment]
The only error I can get from any log is:

`AH01071: Got error 'PHP message: Default exception handler: No valid arguments supplied or incorrect server configuration Debug: \nError code: invalidargorconf\n* line 496 of /lib/setuplib.php: moodle_exception thrown\n* line 3844 of /lib/filelib.php: call to print_error()\n* line 37 of /pluginfile.php: call to file_pluginfile()\n\n'`

I suspect this is from the missing js and CSS.

I have switched the server from Apache to Nginx and upgraded PHP 5.6 to PHP 7 with no effect. 

I noticed this issue has appeared before in the H5P forums but I do not think there is a fix mentioned. 
https://h5p.org/node/20592

**Comment by icc** [comment]
It's difficult to tell exactly what it could be, it sounds like some sort of misconfiguration between the web server and PHP. I would try moving the site to a fresh standard LEMP or LAMP setup to rule out any setup issues.

**Comment by patriclougheed** [comment]
Any chance this can be a bug with Postgres as the database. I just did a fresh install in the same environment but with a mysql database instead and everything works fine now.

**Comment by icc** [comment]
Hm, maybe. Do you know which version of Postgres ?
I can try to do a fresh install and see if the problem is reproducible.

**Comment by patriclougheed** [comment]
9.3.16

**Comment by icc** [comment]
I did a fresh install on Postgres and tried reproducing it – but without running into any issues. So, I guess it must be some combination of things that breaks it.

**Comment by patriclougheed** [comment]
Thanks for trying. I think it might be a combo of Apache and Postgres as I get this error but this is not an issue with Nginx. I tried all the work arounds for security.limit_extensions in PHP with not effect and would expect similar issues with the other plugins. 

[proxy_fcgi:error] [pid 9110:tid 140054085187328]  AH01071: Got error 'Access to the script '/var/www/pluginfile.php/1/mod_hvp/libraries/FontAwesome-4.5/h5p-font-awesome.min.css' has been denied (see security.limit_extensions)\n', referer: /mod/hvp/view.php?id=1438

[proxy_fcgi:error] [pid 9039:tid 140054085187328]   AH01071: Got error 'Access to the script '/var/www/pluginfile.php/1/mod_hvp/libraries/H5P.Accordion-1.0/h5p-accordion.css' has been denied (see security.limit_extensions)\n', referer: /mod/hvp/view.php?id=1438

[proxy_fcgi:error] [pid 9053:tid 140053992867584]   AH01071: Got error 'Access to the script '/var/www/pluginfile.php/1/mod_hvp/libraries/H5P.AdvancedText-1.1/text.js' has been denied (see security.limit_extensions)\n', referer:/mod/hvp/view.php?id=1438

**Comment by icc** [comment]
Ah, I see. I'm not really familiar with the limit_extensions errors, but I'm guessing it might be related to the the rewrite. The URL ends with .js or .css but it's actually the pluginfile.php script serving it, i.e. php is sending the file but the URL isn't ending in .php. This probably means that the SCRIPT_NAME php-fpm is getting is wrong.

In nginx this is handled by the following rewrite:
```
rewrite ^/(.*\.php)(/)(.*)$ /$1?file=/$3 last;
```

**Comment by patriclougheed** [comment]
Yeah... It works fine in Nginx. It is with Apache that the problem is happening. I have lots of activity plugins installed and working fine for years. I have only ever had issues with this plugin.
