### ISSUE TITLE
Feature: "On view" completion criteria

### ISSUE THREAD

**Issue by LukeCarrier** [h5p/h5p-moodle-plugin#134]
Most Moodle activity modules provide a completion criteria which considers the activity complete after its view page has been requested by a student. This option is currently missing from H5P activities. Is the feature already planned, or would a patch to add it be accepted?

For reference, the settings on the modedit page are the following:

> Completion tracking
> Show activity as complete when conditions are met

> Require view
> Student must view this activity to complete it

**Comment by thomasmars** [comment]
There is no plans to add this as far as I know. A patch, given good implementation, would likely be accepted. This sounds like a great addition to the completion tracking.

**Comment by ghkastro** [comment]
Hi there, just ran into this topic
https://docs.moodle.org/dev/Activity_completion_API
So changing the lib.php FEATURE_COMPLETION_TRACKS_VIEWS return false -> return true;
easy, 
but where to implement the $completion = new completion_info($course);
$completion->set_module_viewed($cm);
it says before the Header, ok, but where specifically. any idea?

**Comment by thomasmars** [comment]
Yeah, you're right, it seems like this has already been added in https://github.com/h5p/h5p-moodle-plugin/commit/89e18d76b74c6f4a3e983e2b9f5d9b59bc4959f6. Thanks.
