### ISSUE TITLE
Allow embed code from Moodle H5P-plugin content

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#135]
Hello,

I Would like to see an feature where you could get embed code from Moodle H5P-activity so you could embed the content created in Moodle to other websites.

**Comment by icc** [comment]
Won't this be very unpractical since you have to login on the moodle site first and then navigate back to the other website to be able to see it?

**Comment by austin-powell** [comment]
I could see this being useful as a way to have H5P content built in Moodle to be embedded in other Moodle activities (like a Book or Lesson) rather than have the content be it's own activity.

**Comment by icc** [comment]
That would be #30.

**Comment by cljkoopman** [comment]
It would be great to have that option! Thanks a lot.

**Comment by teacherinpastlife** [comment]
My colleagues are interested in this issue as we would like to point users to the next activity, or loop them to the next Moodle learning object, in order to create a learning path especially with H5P activities. Otherwise, students have to be returned to the main course page and may get "off course".

**Comment by cljkoopman** [comment]
Is the H5P-activity "Column" where you are looking for?

**Comment by teacherinpastlife** [comment]
We are mainly utilizing H5P for the Interactive Video Component.

**Comment by nadavkav** [comment]
We have H5P activities in a Moodle course that are externally shared using LTI with other Moodle systems. maybe that can help you?
