### ISSUE TITLE
Unable to create a new interactive video in the H5P plug-in for Moodle since updating the libraries

### ISSUE THREAD

**Issue by christopherblake** [h5p/h5p-moodle-plugin#136]
I am using Moodle v3.2.1 and since updating to the H5P library release last week I cannot create a new Interactive video activity. When I try to build one I get an error "The H5P library {$a->%library} used in the content is not valid". What is the best way to handle this?

**Comment by nachoan** [comment]
Hi, 
Yes, there is a bug.
At the moment using version 1.0 plugin (without rc) you can clic the second label 'adding an interacction' and save and close the activity.
