### ISSUE TITLE
slug field has no length defined

### ISSUE THREAD

**Issue by ewallah** [h5p/h5p-moodle-plugin#137]
The field slug has no length defined 
FIELD NAME="slug" TYPE="char" NOTNULL="true" SEQUENCE="false" COMMENT="Human readable content identifier that is unique"

As a result:

- admin/tools/dbconvert.php does not work
- php admin/cli/check_database_schema.php generates warning  * column 'slug' length is 255, expected  (C)
- PostgreSQL incompatibility

Simply changing the line into
FIELD NAME="slug" TYPE="char"  LENGTH="255" NOTNULL="true" SEQUENCE="false" COMMENT="Human readable content identifier that is unique"
removes the check_database_schema.php generates warning.

**Comment by fnoks** [comment]
Thank you for your problem report. I have added an issue here: https://h5ptechnology.atlassian.net/browse/HFP-837

**Comment by ewallah** [comment]
Dream on "We take feedback very seriously"

**Comment by thomasmars** [comment]
Hi Ewallah,
I'm sorry, we have clearly upset you, this issue should have been handled sooner.

I could not find the dbconvert.php tool that you mentioned, however I have fixed the warning generated from check_database_schema.php at https://github.com/h5p/h5p-moodle-plugin/commit/5f3396e6180f71a7b68cf40c95e1c22e1430af9a, like you suggested.
I have also done a quick test with Postgres 9.6.3  and could find no issues. The fix will be released together with the next Moodle plugin release.
I'll try to keep a closer eye on these types of issues.

Unfortunately we have quite limited resources so priorities must be made, sometimes we prioritize wrong, thank you for holding us accountable. We also accept pull requests if you find that you have solutions to these problems, which would make the process faster.
