### ISSUE TITLE
When course has h5p-activity backup process is really slow

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#138]
Hello,

If you have a course that has even one H5P-acitivity and make a backup of that course it takes ages, even if that course only has 1 h5p-activity and 1 page-activity and nothing else. So H5P-activities slow the backup process very noticably.

**Comment by Jarvil** [comment]
Taking a backup of 100 Megabytes course with 11 text based course presentation H5P-acitivities took about 10 minutes.

**Comment by falcon-git** [comment]
Ok, this is new to me. I guess it might be a combo of Moodle's file system an all the H5P files, but I don't know. Have raised it [here](https://h5ptechnology.atlassian.net/browse/HFP-839),.

**Comment by falcon-git** [comment]
@icc has answered in Jira. Could you comment there on whether or not his suggested solution (not including libraries in the backup) could work?

**Comment by kraebsli** [comment]
we have a similar problem when deleting h5p-content. after deletion  any other function in a moodle course comes up with a lot of delay. we found out that this is due to using the recycle bin in a moodle installation. is there a way to fix this?

**Comment by icc** [comment]
Please note that the original issue should be fixed in the latest version.

Regarding the recycle bin, I'll look into that – is it when deleting a whole course or just activities? Thanks for letting us know.

**Comment by kraebsli** [comment]
It happens when deleting an h5p activity.

**Comment by icc** [comment]
Hm, is it only for activities with uploaded images or is it for all activities? I tried creating a multiple choice activity and deleting it but didn't notice any delay. Which Moodle version are you on?

**Comment by kraebsli** [comment]
on a fresh h5p install it did not ocurr with timeline activity (2 additional libs installed) but for instance with interactive video (almost 50 libs installed). 
it is when you delete this and thereafter click any other function in the moodle course this function loads very delayed.
I tested this on Moodle 3.1.1+ and Moodle 3.1.5+.
Without recycle bin everything works fine.

**Comment by kraebsli** [comment]
if I put $backup_libraries=0; in backup_hvp_activity_task.class.php it works well. I do not quite understand why I have to backup the libs if I get them from the system or why the process does not go faster.

**Comment by monnardj** [comment]
But then it should work just the same if you put `$CFG->mod_hvp_backup_libraries = 0;` in config.php (assuming you have the latest code).

**Comment by kraebsli** [comment]
yes it does. Thanks!

**Comment by icc** [comment]
You're right, there's no need for the libraries here. I've created an issue to exclude the libraries when using the recycle bin: https://h5ptechnology.atlassian.net/browse/HFP-1081

**Comment by Jarvil** [comment]
Hello,

Any progress? If you still have one h5p-activity on a course backup takes a long time.

**Comment by thomasmars** [comment]
As mentioned earlier you can set `$CFG->mod_hvp_backup_libraries=0;` in your config if you don't wish to backup the libraries during a course backup, which should decrease the backup time significantly.
You can watch https://h5ptechnology.atlassian.net/browse/HFP-1081 for any progress and vote on the issue.

**Comment by bseclier** [comment]
Hello, I'm adding this, just if someone else need it (as I did today), the real sentence you need to write in the config.php file is 
$CFG->mod_hvp_backup_libraries='0';

Don't forget the quotes or it won't work.

**Comment by relecand** [comment]
Problem of slow backups solved with this PR: https://github.com/h5p/moodle-mod_hvp/pull/588
