### ISSUE TITLE
Load the previous content state for the current user

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#14]
`contentUserData` must be set in `view.php`.

`ajax.php` must handle loading of data.

Saving is done in #13 and should be implemented first.

**Comment by thomasmars** [comment]
Fixed in 643e7fc76c6b90c950c9aa49aed83c5ccfc8183a

**Comment by icc** [comment]
We should verify object properties when loading data to avoid PHP notices. Having notices enabled in php.ini makes it easier to spot potential issues. 
```
Notice: Trying to get property of non-object in mod/hvp/classes/content_user_data.php on line 142
```
I think `isset($result->data)` should do the trick for this case.

**Comment by icc** [comment]
Not sure, but _Save Content State_ should probably be disabled by default like in WP and Drupal?

**Comment by thomasmars** [comment]
Yes, probably. Fixed
