### ISSUE TITLE
Deprecated use of stdClass object at message_send

### ISSUE THREAD

**Issue by guillalva06** [h5p/h5p-moodle-plugin#143]
The use of an stdClass object as first parameter of the function message_send was deprecated(See https://tracker.moodle.org/browse/MDL-47162). Now, you have to use a \core\message\message object as parameter.  The function message_send with their wrong object parameter is in look_for_updates.php. Could you replace the wrong parameter?

**Comment by thomasmars** [comment]
Thank you for highlighting this issue, I have created an [issue in the public tracker](https://h5ptechnology.atlassian.net/browse/HFP-873) for fixing this.

**Comment by fnoks** [comment]
This code has already been removed. Therefore closing this one
