### ISSUE TITLE
Breadcrumb and HP5-menu have dissappeared

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#147]
Hello,

If you create a new or update existing H5P-activity the Moodle breadcrumb (navigation trail) and H5P-menu (from the administration block) dissappears.

This concerns Moodle 3.1.5 (Build: 20170313) and **1.0-rc8 (from git master branch)**. This problem doesn't exist in mod_hvp **1.0 2017031300**

How to recreate the problem:

1. Creat a new H5P-activity f.ex. course presentation
2. Save and return to course
3. View the activity
4. Notice how the breadcrumb is missing
5. Notice how in the administration-block there is no H5P-menu

I get this error when I turn debugging on;

```
Coding problem: unsupported modification of PAGE->context from 70 to 10
line 995 of /lib/pagelib.php: call to debugging()
line 881 of /mod/hvp/classes/framework.php: call to moodle_page->set_context()
line 2117 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->alterLibrarySemantics()
line 212 of /mod/hvp/editor/h5peditor.class.php: call to H5PCore->loadLibrarySemantics()
line 142 of /mod/hvp/editor/h5peditor.class.php: call to H5peditor->processField()
line 158 of /mod/hvp/lib.php: call to H5peditor->processParameters()
line 109 of /mod/hvp/lib.php: call to hvp_save_content()
line 571 of /course/modlib.php: call to hvp_update_instance()
line 273 of /course/modedit.php: call to update_moduleinfo()
```

**Comment by icc** [comment]
This should already be fixed by b16cb95. If not, please reopen.
