### ISSUE TITLE
Which capabilities are required to view and use H5P-activity in Moodle?

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#148]
Hello,

Please can you list all the capabilities that are required to view and use H5P-activity on a Moodle course (for example which capabilities student needs to view and use all H5P activities). It seems it needs more than H5P-capabilities (mod/hvp:) to work

mod_hvp 1.0

**Comment by Jarvil** [comment]
Hello,

It seems that

authenticated user needs:

mod/hvp:getcachedassets

student needs:

mod/hvp:getcachedassets
mod/hvp:getcontent
mod/hvp:savecontentuserdata
mod/hvp:saveresults
mod/hvp:viewresults

in mod_hvp 1.0

**Comment by thomasmars** [comment]
Hi, to view content the following capabilities are needed:
mod/hvp:getcachedassets
mod/hvp:getcontent

To save current content state and results:
mod/hvp:savecotnentuserdata
mod/hvp:saveresults
