### ISSUE TITLE
content types not loading on new content creation

### ISSUE THREAD

**Issue by parivajk** [h5p/h5p-moodle-plugin#152]
I have moodle 3.2, apache2, postgres 9.5 and php-5.6.30 installed. Managed to install the H5P plugin without problem and also used the package file to load up all content types as per as instrustions. All setup is on default and I can see the uploaded content types under H5P libraries.

Now, if I log in to the moodle instance as admin and start to edit a course, by adding new Interactive Content the H5P edit for new content is blank there is no type I can select.
I have the following error in apache log just after I click to create a new interactive content:

Default exception handler: Error reading from database Debug: ERROR:  column "hl2.major_version" must appear in the GROUP BY clause or be used in an aggregate function
LINE 6:
       SELECT hl2.machine_name, hl2.major_version, MAX(...
            SELECT hl4.id, hl4.machine_name, hl4.title, hl4.major_version, hl4.minor_version, hl4.patch_version, hl4.has_icon, hl4.restricted FROM mdl_hvp_libraries hl4 JOIN (
		 SELECT hl2.machine_name, hl2.major_version, MAX(hl2.minor_version) AS minor_version  FROM ( SELECT hl.machine_name, MAX(hl.major_version) AS major_version FROM 				mdl_hvp_libraries hl
		            WHERE hl.runnable = 1 
			           GROUP BY hl.machine_name) hl1
			            JOIN mdl_hvp_libraries hl2
			            ON hl1.machine_name = hl2.machine_name
			            AND hl1.major_version = hl2.major_version
			            GROUP BY hl2.machine_name) hl3
			            ON hl4.machine_name = hl3.machine_name
			            AND hl4.major_version = hl3.major_version
			            AND hl4.minor_version = hl3.minor_version
			            GROUP BY hl4.machine_name
[a0rray ()]
Error code: dmlreadexception
* line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 776 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 59 of /mod/hvp/classes/editor_ajax.php: call to pgsql_native_moodle_database->get_records_sql()
* line 459 of /mod/hvp/editor/h5peditor.class.php: call to mod_hvp\\editor_ajax->getLatestLibraryVersions()
* line 399 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5peditor->getLatestGlobalLibrariesData()
* line 97 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5PEditorAjax->getContentTypeCache()
* line 218 of /mod/hvp/ajax.php: call to H5PEditorAjax->action()
, referer: http://MYSERVERIP/moodle/course/modedit.php?add=hvp&type=&course=9&section=1&return=0&sr=0

I understand the sql error message but have no clue as if this coused by setup problems or I sould start and look into H5P or moodle php code and change that, but I hope the former.

Also I tried to upload an example dowloaded from the site, the upload works but when click save I get the following error from moodle:
"The H5P library {$a->%library} used in the content is not valid"

Can someone please point me to the right direction how to solve this, thank you in advance.

**Comment by icc** [comment]
Try using the latest version of H5P plugin for Moodle

**Comment by parivajk** [comment]
Hi, thank you for your promt response!
When I first installed the plugin I download it from moodle repo https://moodle.org/plugins/mod_hvp
and installed it as a zip file, so I guess that that point that was the latest installable version.

Anyways I downlaoded again and installed/updated the plugin and now it works so far so good, so thank you for your input!
