### ISSUE TITLE
xAPI support

### ISSUE THREAD

**Issue by davidpesce** [h5p/h5p-moodle-plugin#153]
I dug a bit through your issues (relating to xAPI) and it doesn't appear clear as to how to send xAPI statements directly from the plugin. There is a setting within 'H5P Settings' to 'Enable LRS dependent content types', but nothing more. I have a question set (created within this plugin) that I'd like to report out to an LRS. How would I do this?

**Comment by falcon-git** [comment]
Does this help? https://h5p.org/documentation/for-authors/analyzing-results-and-answers

**Comment by davidpesce** [comment]
It looks like you have support for WP and Drupal, but I'm curious about Moodle.

**Comment by falcon-git** [comment]
The H5P Core team hasn't added support for this to any publishing system, but WordPress and Drupal developers have done that for those systems, and I think work is in progress for Moodle. I tried to find the relevant issue, but I couldn't.

**Comment by falcon-git** [comment]
It wasn't an issue, but a PR, and I see you've already found it - https://github.com/h5p/h5p-moodle-plugin/pull/114

**Comment by davidpesce** [comment]
Thanks, Falcon! I did some additional digging and it looks like @thomasmars is also doing some work on the reporting branch. @thomasmars any info on the goals and status of that branch?

**Comment by thomasmars** [comment]
It is, and has been possible for a while to view reports in Moodle. Please re-open this issue if this issue was concerning something else.
