### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by 2shediac** [h5p/h5p-moodle-plugin#155]
Hi - trying to install - https://github.com/h5p/h5p-moodle-plugin/commit/cffb7db23342bc2e5ae3651003237be0ac393d35, 

Warning: require_once(mod/hvp/library/h5p.classes.php): failed to open stream: No such file or directory in mod/hvp/autoloader.php on line 57

the file h5p.classes.php is missing from the library folder.

**Comment by icc** [comment]
If you cloned the git repo remember to run `git submodule update --init`

**Comment by 2shediac** [comment]
Thanks
