### ISSUE TITLE
missing string

### ISSUE THREAD

**Issue by martinvivek** [h5p/h5p-moodle-plugin#156]
Invalid get_string() identifier: 'messageprovider:updates' or component 'mod_hvp'. Perhaps you are missing $string['messageprovider:updates'] = ''; in mod/hvp/lang/en/hvp.php?

**Comment by thomasmars** [comment]
It is indeed missing. Thank you for reporting this. We would love a pull request for it

**Comment by thomasmars** [comment]
Please re-open if this is still an issue, could not find any documentation on it.
