### ISSUE TITLE
Interactive video with no interactions 

### ISSUE THREAD

**Issue by lihidor** [h5p/h5p-moodle-plugin#157]
Hi,
In some situations we want the lecturer to integrate  a video in a course with no interactions in first level (should be added later).
When choosing a video and trying to save the activity settings with no interactions we get this error-
"The H5P library {$a->%library} used in the content is not valid".
Thanks,
Lihi.

**Comment by falcon-git** [comment]
Hi Lihi,

Thank you for reporting. This is actually a known problem and solved in the latest version of Interactive Video. You may try to do the same on H5P.org, it used to fail, but it works now.
