### ISSUE TITLE
Site could not be registered with the hub.

### ISSUE THREAD

**Issue by watcanz** [h5p/h5p-moodle-plugin#158]
I am getting this message... not sure why.

Site could not be registered with the hub. Please contact your site administrator.
The H5P Hub has been disabled until this problem can be resolved. You may still upload libraries through the "H5P Libraries" page.

Thanks

**Comment by thomasmars** [comment]
Hi, when does this happen ?

The reason for this is that your server is not able to communicate with H5P.org. There could be many reasons for this. Please verify that your server can communicate with external APIs.
When you have done this you can go to the H5P Settings page, which can be found in  Site Administration -> Plugins -> Plugins Overview. There you can re-enable the H5P Hub with a checkbox.

If you still are not able to register with the Hub, turn on [development debugging in Moodle](https://docs.moodle.org/33/en/Debugging) and check if Moodle displays any errors when you do this. Also please let us know the version of Moodle, PHP and the H5P Plugin you are using.

**Comment by watcanz** [comment]
It is a curl connection error.  However, curl is working fine.  his plugin
works on other servers I run.  I wonder if my firewall is blocking your
h5p.org site for some reason.  What is the IP that the plugin tries to
connect to?  I will try whitelisting it.

Jeff

**Comment by thomasmars** [comment]
You can ping h5p.org for the IP. It should be 139.59.212.216.

**Comment by fukyma** [comment]
Solved this problem in my moodle setting. My moddle got blocked by Web Proxy in Site Administration-->Server --> http --> Web Proxy. My server use proxy but the port was incorrect.
