### ISSUE TITLE
branch tag 1.4

### ISSUE THREAD

**Issue by tijcolem** [h5p/h5p-moodle-plugin#161]
Noticed that in tagged branch 1.4 version.php still has the following. Might need to be updated for 1.4? 
$plugin->version   = 2017052400;
$plugin->requires  = 2013051403;
$plugin->cron      = 0;
$plugin->component = 'mod_hvp';
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '1.3';

**Comment by thomasmars** [comment]
Should be fixed now, thanks for reporting this.
