### ISSUE TITLE
Critical bug found in mod_hvp 1.4 & Moodle 3.1 course completion

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#163]
Hello,

I have found very critical bug in mod_hvp 1.4(2017060600) & Moodle 3.1.6 (Build: 20170508) users get course completed marking even if they "fail" against activity grade to pass setting.

Here is how to recreate;

1. Create a H5P -activity f.ex course presentation
2. Check that the maximum grade setting is 10,0
3. Create a f.ex. multiple choice question with 4 choices from which 2 are correct and 2 are not so if you answer all two right you will get grade 4.0
4. Under "Activity completion"-title in "Completion tracking"-dropdown menu select "show this activity complete when conditions are met" and select also "Student must receive a grade to complete this activity"
5. Save and close 

6. Open course from the administration block -> course administration -> course completion 
7. Check that under "general" in "Completion requirements" -dropdownmenu "course is complete when ALL condition are met" is selected.
8. Expand the "Condition: Activity completion"-title and select the H5P-activity you created
9. Save changes

10. From the administration-block select -> course administration -> grades
11. Turn editing on from the upper right corner
12.Click the cogwheel-icon (settings) unders the H5P you have created
13. Press "Show more..." link
14. Set "Grade to pass" to 4.0
15. Save changes.

16. Complete the H5P with student1 that answers all two questions right and gets grade 4.0
17. Complete the H5P with a student2 by selecting only 1 right answer so that he gets grade 2.0

18. Return to the course as administrator/teacher and select reports -> course completion. Notice that student2 has a red marking (did not achieve grade pass grade) and student1 has green marking (achieved pass grade)

19. Wait for the course completion marking to be generated, if your Moodle Cron is ran at 1 minute interval this takes 2 minutes.

20. Refresh the page with F5 and notice that they both receive "course completion"-marking even when student2 shoudn't get it because he failed against grade to pass.
![grade0](https://user-images.githubusercontent.com/15193418/27674288-b5faf480-5cad-11e7-8bb9-5a036a088515.PNG)
![grade1](https://user-images.githubusercontent.com/15193418/27674290-b9167504-5cad-11e7-97e7-18ebe343537e.PNG)
![grade3](https://user-images.githubusercontent.com/15193418/27674293-bb9d1526-5cad-11e7-806b-652135e2c927.png)
![grade4](https://user-images.githubusercontent.com/15193418/27674294-bdc95e86-5cad-11e7-9585-2ad7e7ec48a7.png)

**Comment by thomasmars** [comment]
Hi, I tested this and confirm that this is happening.
However I'm not sure if it is a bug.
To me it seems like the only criteria for an activity to be completed is that the student must receive a grade to complete the activity, like you checked off in the "activity completion" header within the H5P activity.
This has a tooltip which says: "If enabled, the activity is considered complete when a student receives a grade. Pass and fail icons may be displayed if a pass grade for the activity has been set."
Which I interpret like the activity is considered complete when you get any grade.

Our Course Completion criteria is only that the Activity completion criteria of the H5P activity is cleared, which it will be with any grade.
So this is why the course is considered completed, even though you did not reach the "passing grade".

If you want to more granularly control over how many points/grades are required to pass the course you can follow these steps:

1) Go to block: Administration -> Gradebook setup
2) Click "view" to enter the "Grader report"
3) Press "Turn editing on"
4) Press the cogwheel of the course name.
5) Under the "Category total" header press "Show more"
6) Find "Grade to pass", and type in "4.00"
7) Go to the course completion settings Administration -> course completion
8) Check "Enable" under the "Condition: Course grade" header
9) Save changes
7) Find the Course Completion report under Administration -> reports -> course completion
8) Make sure cron.php is run
9) Observe that Course completion will not be ticked for the student that did not have a passing grade.

Feel free to re-open this issue if you disagree with this being the intended behaviour, and have some suggestions for how this should be.

**Comment by Jarvil** [comment]
That would be great

**Comment by Jarvil** [comment]
Also setting grade to 4.0 for whole grade category won't work because you can have multiple activities on the course.

**Comment by thomasmars** [comment]
Excellent, could you create a feature request for a new activity completion criteria for passing grade at the h5p.org forums, which is the central place we track feature requests. This should increase the likelihood that the feature is picked up and implemented.

**Comment by Jarvil** [comment]
Hello, 

Any progress on https://h5ptechnology.atlassian.net/browse/HFP-1853 @thomasmars

**Comment by thomasmars** [comment]
Hi Jarvil,
Unfortunately we have not been able to prioritize this issue yet, sorry. We would gratefully accept pull requests for this.

**Comment by lrodneywu** [comment]
Hi @Jarvil @thomasmars ,

Here at https://warwick.ac.uk/ we have created the following PR relating to this issue as we too required this functionality; https://github.com/h5p/h5p-moodle-plugin/pull/288.
