### ISSUE TITLE
Save state data not working

### ISSUE THREAD

**Issue by elearningdave** [h5p/h5p-moodle-plugin#166]
I read about this feature, so turned it on in the plugin settings.
Tested it by starting a Find Multiple Hotspots activity (scored 2/6), then went straight back to moodle course by clicking the breadcrumb link at the top of the page, clicked h5p activity link again - clicked another valid hotspot, and it's forgotten the score from last time

**Comment by icc** [comment]
I don't believe this content type supports that feature. But it's best if you ask/create an issue on the project's GitHub page so that the author sees it: [lukemuller/h5p-image-multiple-hotspot-question](https://github.com/lukemuller/h5p-image-multiple-hotspot-question)
