### ISSUE TITLE
Assign teacher role to student to let edit H5P activity

### ISSUE THREAD

**Issue by lucaboesch** [h5p/h5p-moodle-plugin#169]
I'd like to assign the trainer role to a student for a H5P activity (e.g. she/he should fill up dialog cards).
When I do "Locally assigned roles", add the teacher role to the student and the student clicks the "Administration -> Edit settings",
the cards editor doesn't show up and just "Error, unable to load libraries." is displayed under "Editor". In the sources you see a 403 response on the culprit ajax.php call and the response says

`{"success":false,"message":"You do not have permission to view the content types."}`

.

To me, the issue lays in checking for the hvp:addinstance capability as prerequisite to show the libraries.

`    case 'libraries':`
&nbsp;&nbsp;`        if (!\mod_hvp\framework::has_access('addinstance', 'nopermissiontoviewcontenttypes')) {`
&nbsp;&nbsp;`            break;`
`        }`

in ajax.php, calling

`    public static function has_access($cap, $error) {`
&nbsp;&nbsp;`      $contextid = required_param('contextId', PARAM_RAW);`
&nbsp;&nbsp;`      $context = \context::instance_by_id($contextid);`
&nbsp;&nbsp;`      if (!has_capability("mod/hvp:$cap", $context)) {`
&nbsp;&nbsp;&nbsp;&nbsp;`          \H5PCore::ajaxError(get_string($error, 'hvp'));`
&nbsp;&nbsp;&nbsp;&nbsp;`          http_response_code(403);`
&nbsp;&nbsp;&nbsp;&nbsp;`          return false;`
&nbsp;&nbsp;`      }`

(in classes/framework.php)

is to blame.

hvp:addinstance targets the contextlevel CONTEXT_COURSE. It is not passed over to the locally assigned role in the CONTEXT_MODULE context.
I think it would be better to check for a CONTEXT_MODULE capability, like 'getcachedassets', or create a new one like 'editinstance' or just 'edit'.

Or am I just dead wrong and doing something the wrong way?

How do you guys allow students to edit H5P?

**Comment by thomasmars** [comment]
I just created a new role, e.g. "Teacher assistant", based on the "student" role.
Gave it the "Manage activities" capability and "hvp:addinstance" capability, then assigned this role to one of the students and he is able to edit H5Ps within the course. Is this not what you want ?

I'm not sure why we would want the addinstance to have the module context, then you will not be able to more granularly define permissions for each course. Please correct me if I'm mistaken.

**Comment by lucaboesch** [comment]
If you would let the student edit the H5P in section 1 of your course, but just that one. She/he wouldn't be able to edit other H5P.
So basically you would assign the role just for this one H5P activity and not for the entire course.
(Was 'module' the wrong term?)

Do you see what I mean? That's not exactly what you were achieving, but I thank you for your kind response and for your time.

**Comment by thomasmars** [comment]
Thanks for the clarification. It would indeed help to change the context sent in to the module context.
I have created an issue for this in the public tracker, if you want to make a pull request for this that would be very nice, otherwise I don't know when the issue can be prioritized, but it should certainly be fixed.
Thanks again for pointing this out, the issue can be found at: https://h5ptechnology.atlassian.net/browse/HFP-1433

**Comment by icc** [comment]
This has now been fixed and will be part of the next version of the plugin.
