### ISSUE TITLE
Add support for the Gradebook API

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#17]
Make sure completed events from the content is sent to the gradebook.

https://docs.moodle.org/dev/Gradebook_API

**Comment by icc** [comment]
Do we need to add `grade` to the hvp table?

**Comment by thomasmars** [comment]
I don't think so, that would mean we would have to know max grade for the H5P when we add it, which we can't.

**Comment by icc** [comment]
I think the implemented solution works OK, but I'm no advanced Moodle user so we'll have to leave some room for feedback from more experienced users.
