### ISSUE TITLE
git and zip are different

### ISSUE THREAD

**Issue by andreasschenkel** [h5p/h5p-moodle-plugin#170]
When I use the moodle-plugin for h5p then there is a bug when I am using the git-version, then I can not open the menue "website-administration"
When clicking on the link websiteadministration then the loading_small.gif is shown but the menue does not open.
With the zip-File the plugin works fine.
moodle 3.1.8  but also in older version this bug exists

**Comment by thomasmars** [comment]
Hi,
I have tried to reproduce this, but I'm unable to.
I'm using the git version, and can enter the "Site administration" menu.
If the "website-administration" is a different menu, please explain where I can find it and add a screenshot.
I can't proceed any further with this bug without more information, so please let me know some detailed steps to
reproduce this on a fresh installation, together with your setup for installing H5P, where you have placed it and
any other information that may deviate from a standard installation. Please also provide your PHP error log and console log
from when you are able to reproduce the bug.
Thanks for reporting this.

**Comment by icc** [comment]
Make sure that you update the submodules after cloning: 
`git submodule update --init`
