### ISSUE TITLE
Error when adding content in Moodle 3.1

### ISSUE THREAD

**Issue by peterdobinson** [h5p/h5p-moodle-plugin#174]
Hi All,
I have installed the H5P plugin onto a Moodle 3.1 instance as per instructions, however when trying to save the activity settings on /course/modedit.php I get the error under the editor section: The H5P library {$a->%library} used in the content is not valid

Moodle version: 3.1.3 0161215
H5P version: 2017083100

**Comment by icc** [comment]
Hi,
Are you trying to create a new activity or are you updating an existing one?
Is the content working after the error?

Try having the browser's console open (Ctrl+Shift+J in Chrome) when creating/editing the content and saving. Watch out for any error messages in red.

**Comment by peterdobinson** [comment]
Hi there,

I am creating a new one. When pressing save there is no console/debug error.

**Comment by peterdobinson** [comment]
HI there,

I am trying to create a new activity, the console error is:

h5peditor-editor.js?ver=2017083100:69 Uncaught TypeError: Cannot read property 'LibrarySelector' of undefined
    at HTMLIFrameElement.<anonymous> (h5peditor-editor.js?ver=2017083100:69)
    at HTMLIFrameElement.dispatch (jquery.js?ver=2017083100:2)
    at HTMLIFrameElement.v.handle (jquery.js?ver=2017083100:2)
    at HTMLDivElement.<anonymous> (jquery-1.12.1.min.js:48)
    at Ha (jquery-1.12.1.min.js:47)
    at n.fn.init.append (jquery-1.12.1.min.js:48)
    at n.fn.init.wrapAll (jquery-1.12.1.min.js:71)
    at HTMLFieldSetElement.<anonymous> (jquery-1.12.1.min.js:71)
    at Function.each (jquery-1.12.1.min.js:1)
    at n.fn.init.each (jquery-1.12.1.min.js:1)
(anonymous) @ h5peditor-editor.js?ver=2017083100:69
dispatch @ jquery.js?ver=2017083100:2
v.handle @ jquery.js?ver=2017083100:2
(anonymous) @ jquery-1.12.1.min.js:48
Ha @ jquery-1.12.1.min.js:47
append @ jquery-1.12.1.min.js:48
wrapAll @ jquery-1.12.1.min.js:71
(anonymous) @ jquery-1.12.1.min.js:71
each @ jquery-1.12.1.min.js:1
each @ jquery-1.12.1.min.js:1
wrap @ jquery-1.12.1.min.js:71
(anonymous) @ first.js:99
i @ jquery-1.12.1.min.js:25
add @ jquery-1.12.1.min.js:25
n.fn.ready @ jquery-1.12.1.min.js:25
snapInit @ first.js:99
(anonymous) @ modedit.php:510
execCb @ require.min.js:27
check @ require.min.js:27
enable @ require.min.js:27
init @ require.min.js:27
(anonymous) @ require.min.js:27
setTimeout (async)
(anonymous) @ require.min.js:27
g @ require.min.js:27
requirejs @ require.min.js:27
(anonymous) @ modedit.php:510
execCb @ require.min.js:27
check @ require.min.js:27
(anonymous) @ require.min.js:27
(anonymous) @ require.min.js:9
(anonymous) @ require.min.js:27
v @ require.min.js:3
emit @ require.min.js:27
check @ require.min.js:27
(anonymous) @ require.min.js:27
(anonymous) @ require.min.js:9
(anonymous) @ require.min.js:27
v @ require.min.js:3
emit @ require.min.js:27
check @ require.min.js:27
(anonymous) @ require.min.js:27
(anonymous) @ require.min.js:9
(anonymous) @ require.min.js:27
v @ require.min.js:3
emit @ require.min.js:27
check @ require.min.js:27
enable @ require.min.js:27
init @ require.min.js:27
E @ require.min.js:25
completeLoad @ require.min.js:27
onScriptLoad @ require.min.js:27

**Comment by icc** [comment]
That is strange. Does it work if you try to create content on [h5p.org](https://h5p.org/node/add/h5p-content)?
