### ISSUE TITLE
Moodle_Failed to load resource: the server responded with status of 500-Ajax request failed 

### ISSUE THREAD

**Issue by talicharlotte** [h5p/h5p-moodle-plugin#178]
I downloaded the latest version of H5P last week, but can't seem to get the editor to load for any of the resources. I'm able to create a project and select open, but no editor. For now I am only able to make content inH5P and embed it in Moodle, untill I can find someone more advanced to help me sort out the problem.  I'm able to upload a H5P file, but it also won't display in lesson vies.

My Browser's console reports the following error: Failed to load resource: the server responded with a status of 500 (Internal Server Error) 

Ajax request failed 

The source is: /hvp/editor/scripts/h5peditor.js?ver=2017083100

I was able to increase the  upload_max_filesize and post_max_size.  to 64M. Thats the max that my host will allow. I can also confirm that the php extension ZipArchive is afailable, but I couldn't find or locate mbstring. I also have no idea how to solve this if that is causing the problem since my server is an Apatche web server and there is no php.ini file can only do overides via a .htaccess files. For the moment I'm stuck.

**Comment by icc** [comment]
You must check your web server's error log file to see the actual message behind the 500 error. 
Alternatively, you could enable debugging temporarily to have the errors printed, though it may not work for AJAX. To do this you have to add the following to your config.php:
```php
@error_reporting(E_ALL | E_STRICT);   // NOT FOR PRODUCTION SERVERS!
@ini_set('display_errors', '1');         // NOT FOR PRODUCTION SERVERS!
$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION$
$CFG->debugdisplay = 1;              // NOT FOR PRODUCTION SERVERS!
```

Where did you download the plugin from and which PHP version are you using?

**Comment by talicharlotte** [comment]
1. Okay this is the error log:
[06-Nov-2017 14:53:52 Africa/Johannesburg] PHP Fatal error:  Call to a member function get_content() on boolean in /usr/www/users/kaleidfmja/learn/mod/hvp/classes/file_storage.php on line 364
[06-Nov-2017 14:59:01 Africa/Johannesburg] PHP Notice:  Undefined index: SCRIPT_NAME in /usr/www/users/kaleidfmja/learn/auth/cas/CAS/CAS.php on line 45
[06-Nov-2017 14:59:01 Africa/Johannesburg] PHP Notice:  Undefined index: QUERY_STRING in /usr/www/users/kaleidfmja/learn/auth/cas/CAS/CAS.php on line 45

2. The plugin was dowloaded from Moodles plugins version 1.5 (2017083100)
3. PHP version 5.6

**Comment by thomasmars** [comment]
Since you're likely missing the "mbstring" extension libraries will not validate, and thus not be installed.
The error you're seeing in your php error log is related to not finding a file, because it probably was not able to install the library, since the library could not be validated, since you're missing the "mbstring" extension.
Please try to install the extension on your server by following a php guide, or contact your host provider if you're not hosting it yourself or can't change the php setup. Please report back after you have tried this.
Thank you for your detailed error description. I have created an issue for giving better error message when the file can not be found at the public issue tracker: https://h5ptechnology.atlassian.net/browse/HFP-1725

**Comment by talicharlotte** [comment]
thomasmars! fancy running into you here. Hehe, bad joke, sorry. It's been a long day. So I've given my host provider a call and then send them an email with all the details they requested it's in their hands now. 

For future reference I'm hosting on a a shared server running Apache 2.2, and therefore have limited access to PHP config. That is probably what started the issue. 

That and the fact that I'm a graphic designer with limited programming knowledge, but that is why I've been stalking you on every possible platform and scanning every form with such determination. I'm so exited about what you are doing with H5P. I really want to get this to work. The functionality is amazing and you can make it look fabulous! Not normally a top priority seen in most Moodle apps. You have managed to create the best of both worlds. Will let you know what the outcome is with my provider (or move to a more suited host if I must)

Thank you so much for all the help, time and patience. 

Is there a paypal account for H5P? I did'nt see a link on the moodle plugins page.

**Comment by thomasmars** [comment]
I'm happy you like H5P, I hope we can help you resolve this :)
