### ISSUE TITLE
Deleting a H5P activity in Moodle couses a session lock for the user

### ISSUE THREAD

**Issue by memetoec** [h5p/h5p-moodle-plugin#179]
Hi!

We have a strange error with the H5P module. 

When we want to delete an activity, we click delete and confirm that the deletion is correct. After confirming the deletion, Moodle is loading at the same page until we get a session lock on the user. When we login to Moodle after the session lock is finished, we can see that the activity is deleted. When we log in with another user while the session lock for the other user still is active, we can see that the activity hasn't been deleted. 

We shouldn't get a session lock because of an deletion, do you have any solutions for this? Is this case known from other sites?

**Comment by thomasmars** [comment]
Hi, I'm not able to reproduce this.
Can you check your php error log for any errors that may be occuring when you are deleting the activities ?
Could you have some plugins that may be interfering with the deletion ?

**Comment by Jbach12** [comment]
Hi, can I ask if this has been resolved @memetoec ? I have just had exactly this happen to me today and need to know what the fix is if you can assist?
Thanks,
Jayne

**Comment by thomasmars** [comment]
Please re-open this issue with detailed steps to replicate if this is still a problem.
