### ISSUE TITLE
Plugin version 1.5

### ISSUE THREAD

**Issue by pwelham** [h5p/h5p-moodle-plugin#180]
In order to test this we installed it on one of our development environments (a copy of our live Moodle environment) and updated all the content libraries.  We're using Moodle 3.2.3.

However, when one user tried to download content that she had created recently...

https://h5p.org/node/124166

and the 'Course Presentation' example from H5P website...

https://h5p.org/presentation

...she got a 'library used in the context is not valid' error message:

![library error](https://user-images.githubusercontent.com/10267573/32670648-57bdd5d8-c63c-11e7-8940-d7e52eef9bc0.jpg)

Could you please advise us what the cause may be?  We are keen to get the new version installed on 'live' but need to get this resolved first.

Thank you.

Best regards

Peter

**Comment by icc** [comment]
Hi Peter,

Please make sure that the user presses the 'Use' button after selecting the file, but before saving the activity. The content of the file should load in the editor before the form is saved.
