### ISSUE TITLE
Activity being marked as completed

### ISSUE THREAD

**Issue by DennisWiencken** [h5p/h5p-moodle-plugin#182]
It seems that a question set it being marked as completed in Moodle even if the users did not get the passing grade.

In our set up users should get 100% to pass the quiz/questionset and when the quiz is completed the course would be marked as complete.

However it seems that users that answer every question but gets a grade under 100% is marked as "Completed (did not achieve pass grade)" and the course is still marked as complete.

**Comment by thomasmars** [comment]
Hi,
Make sure you have set "Grade to pass" in gradebook setup when editing a grade item. You also must make sure to set the following options in the settings of the activity itself under "Activity Completion" when you have enabled Completion settings for the course:
- Completion tracking: "Show activity as complete when conditions are met"
- And check Require grade: "Student must receive a grade to complete this activity"

This will require the student to reach the "pass grade" before the activity is counted as completed towards the course completion goal.
I just tested this and there shoul be no problems, let me know if you're not able to configure this properly and where you are having troubles. Thanks.
