### ISSUE TITLE
Safari & iOS issue

### ISSUE THREAD

**Issue by AurelienDM** [h5p/h5p-moodle-plugin#185]
The plugin H5P doesn't work well with Safari and iOS (I have not tried Android yet) : the activity does not load.
Please check this URL : https://moodle.aflahaye.nl/exercices

**Comment by timothyylim** [comment]
It doesn't seem to work on Chrome either. I'm sorry it took so long for me to get round to replying this. Have you managed to find a solution?

**Comment by AurelienDM** [comment]
@timothyylim This issue is related to this one : https://github.com/h5p/h5p-moodle-plugin/issues/63
The plugin isn't working at all now.

**Comment by timothyylim** [comment]
As @icc, mentioned in #63 it may be due to your web server set up and not H5P itself. Try speaking to your admin/server responsible. Let me know if you can make any progress in that direction.

**Comment by dryize** [comment]
Safari on iOS (may be chrome as well), does not send any cookies along with the requests (ajax). Thus fail to load the resources.

**Comment by icc** [comment]
@dryize Are you using different domains? I believe it should send the cookie if you've visited the domain previously.

(Also, note that there is a setting for fixing this in Safari under Privacy/Security menu tab -- but not very convenient for all visitors/students to enable)
