### ISSUE TITLE
Image Sequencing library doesn't give grade for Moodle

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#186]
Hello,

It seems that Image Secuquencing -library gives users points f.ex 3/3 points but doesn't deliver these to moodle grade book / grader report like f.ex course presentation does.

**Comment by thomasmars** [comment]
Hi, Image Sequencing does not implement functionality for triggering the score to the gradebook. This is a missing feature of the "Image Sequencing" library. Please create an issue in that repository instead: https://github.com/jithin-space/h5p-ImageSequencing
