### ISSUE TITLE
Upgrading H5P doesn't respect settings

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#198]
Hello,

When I'm upgrading H5P-plugin in Moodle from version that doesn't have options

- mod_hvp | export 
- mod_hvp | embed

to a new version 1.7 I do the following procedure;

1. Upgrade the plugin
2. During the configuration phase in Moodle I set embed and download settings "default off, controlled by author"
3. Then what happens is that these are turned on on all existing H5P-acitivities that has been created before.

 Is this a bug? Shoudn't the plugin respect the choice I make regarding existing H5P-activities? @timothyylim

**Comment by BV52** [comment]
Hi @Jarvil 

I filed a report and you can follow it [here](https://h5ptechnology.atlassian.net/projects/HFP/issues/HFP-1955).

-BV52
