### ISSUE TITLE
White text doesn't show up in editor (which has white background)

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#199]
Hello,

if you set the font color to white in H5P editor you cannot see it anymore because the editor background is white, this needs to be fixed. Tested with mod_hvp 1.7

**Comment by timothyylim** [comment]
Hi @Jarvil, I understand how this can be very frustrating. Unfortunately, we can't give this a high priority right now but we'll be open to pull requests that solve it.

**Comment by Jarvil** [comment]
Hello,

So is this fixed in future release or why did you close it?

**Comment by thomasmars** [comment]
For text where there is text-background, you can use that to make the text visible. This is not an issue with the h5p moodle plugin. If there are content types that don't allow to set the background of the text please open an issue there.
If you would like to help, please make suggestions for how this can be solved universally for the content types, or create a pull request like @timothyylim suggested.
