### ISSUE TITLE
Discussion: Plugin upgrade

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#2]
In order to upgrade the plugin to use latest H5P PHP library and Moodle version, some of the database tables need to be altered.

Is the plugin currently being used somewhere? If not, there's no point in wasting effort to make an upgrade path. I'll just add the alterations straight to the installation feature.

In case the plugin *is* being used, would someone be able to duplicate it into a test environment and test the upgrade path?

**Comment by falcon-git** [comment]
I think we can assume that it is not being used

**Comment by juho-jaakkola** [comment]
Ok. I'll leave the issue open for a bit more just in case someone has differing information.

**Comment by juho-jaakkola** [comment]
No-one has had differing information and also the README now warns that the plugin is not production ready, so I believe it is safe to close the issue.
