### ISSUE TITLE
H5P broken grading. Says 0/1 yet shows that they got correct answers.

### ISSUE THREAD

**Issue by Summersa** [h5p/h5p-moodle-plugin#202]
![image](https://user-images.githubusercontent.com/15676683/40630663-9a4966c8-6291-11e8-8159-d833660707f5.png)

I could not possible test how often this happens, but we get a couple calls about this a day.

This happens with all multiple choice questions.

The only other question type we have is true and false however, but they seem all to work perfectly.

**Comment by BV52** [comment]
Hi @Summersa ,

I've created a separate post in the forums for you. You can access it [here](https://h5p.org/node/252181).

-BV52
