### ISSUE TITLE
h5p moodle plugin version 1.9 has problem in showing grade details

### ISSUE THREAD

**Issue by elahehab** [h5p/h5p-moodle-plugin#203]
In version 1.9 of moodle plugin when grading book is shown and the magnifier icon is clicked this message is shown: "This user hasn't submitted an answer to the H5P yet" unless the activity has been done and it has a grade.

**Comment by thomasmars** [comment]
Yes, what behaviour would you expect ?

**Comment by elahehab** [comment]
I expect to see the grade details as I can see in previous versions. A table with this fields: 
User | Score | Maximum Score | Finished | 
like [this image](http://uupload.ir/files/3b1i_screenshot_from_2018-06-30_07-45-21.png) (it shows the result in moodle plugin version 1.6)

**Comment by icc** [comment]
I've double checked this and it appears to be working. Could you please check that you have the correct role/user and that students have answered the activity?

**Comment by elahehab** [comment]
I tried to change teacher's role permissions and I'm sure the student answered this activity (she has a grade in grades book). But still I see [this picture](http://uupload.ir/files/qbj_screenshot_from_2018-07-11_09-33-16.png) when I click on magnifier.

**Comment by icc** [comment]
That is strange. What happens if you click the task name at the top of the gradebook? Do you see the students score there?

**Comment by elahehab** [comment]
This is my grade book view: ([grade book view](http://uupload.ir/files/970m_screenshot_from_2018-07-11_12-24-30.png))
This is the page that I see when I click on task name at the top of the grade book: ([page view](http://uupload.ir/files/9yp_screenshot_from_2018-07-11_12-25-40.png))
As you can see no user is listed in the table.

**Comment by icc** [comment]
This is not normal and appear to be working for other Moodle installations. You should try to check your web server's error_log file or turn on debugging in config.php to see if you get any error messages:
```
@error_reporting(E_ALL | E_STRICT);
@ini_set('display_errors', '1');
$CFG->debug = (E_ALL | E_STRICT);
$CFG->debugdisplay = 1;
```

**Comment by thomasmars** [comment]
Please re-open with additional information if you're still experiencing this.
