### ISSUE TITLE
prequalify a pull request: Make H5P Content avaliable in moodle mobile 3.5

### ISSUE THREAD

**Issue by Andmat7** [h5p/h5p-moodle-plugin#204]
I want to prequalify a pull request related to the following:
**User story:**
As a user I want to access H5P content from the Moodle mobile app so that I can learn on the go.
Current functionality sends the user to open a browser page in order to access H5P content.

**UX:**
H5P content should retain usability and responsiveness when launched in Moodle mobile app.

**Technical solution:**
Update the H5P Moodle plugin according to the new moodle mobile app´s documentation ( https://docs.moodle.org/dev/Mobile_support_for_plugins ). It is expected to convert view.php into and ionic 3 template with their respective javascript libraries.

Offline functionality should be developed as a different issue.

**Comment by thomasmars** [comment]
Version 1.17 of the plugin enables displaying H5P content in the moodle mobile app. Offline is not supported yet.
