### ISSUE TITLE
Make H5P communicate with Course Overview block

### ISSUE THREAD

**Issue by pkgh** [h5p/h5p-moodle-plugin#206]
I just started playing with H5P, and would love to make it communicate with the Moodle Course Overview (Moodle's default "Dashboard" block). One way in which this can be done is when plugins send to the course overview block the date information set via Activity Completion > Expect Completed by. I have followed that path successfully with LTI tools, but not with the H5P plugin. Could something be done about this? I'm really struggling to make our Moodle Dashboard maximally informative about what the students are due to do.. Thanks for any concern you can give to this.

Using Moodle 3.5.1 and the latest H5P package.

**Comment by thomasmars** [comment]
This sounds like a great idea. Do you have any resources on how this could be achieved ?

**Comment by pkgh** [comment]
Not really beyond what I have already said. I'm not really a coder..

**Comment by thomasmars** [comment]
I have created an issue for this in our JIRA issue tracker where you can follow along the progress: https://h5ptechnology.atlassian.net/browse/HFP-2153
