### ISSUE TITLE
H5P 1.9 doesn't work correctly with PHP 5.6 (which is Moodle 3.3 requirement)

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#207]
Hello,

H5P version 1.9 causes problem with Moodle version 3.3 because it uses PHP7 variables but Moodle 3.3 requires only PHP 5.6 version.

**Issue is similar to:**

[https://github.com/intelliboard/intelliboard/issues/16 ](url)

Problem occurs with Moodle GDPR-tools when uses requests his/hers data.

The user receives an error

**

- Exception occured while processing privacy data

- Exception occured while calling mod_hvp\privacy\provider::get_contexts_for_userid.
- This means that plugin mod_hvp did not complete processing data. Below you can find exception information that can be passed to the plugin developer.

- Koodivirhe havaittu, ohjelmoijan pitää korjata se: PHP catchable fatal error

- #0 /var/www/moodle/33x/mod/hvp/classes/privacy/provider.php(118): default_error_handler(4096, 'Argument 1 pass...', '/var/www/moodle...', 118, Array)
- #1 /var/www/moodle/33x/privacy/classes/local/legacy_polyfill.php(76): mod_hvp\privacy\provider::_get_contexts_for_userid('117')
- #2 [internal function]: mod_hvp\privacy\provider::get_contexts_for_userid('117')
- #3 /var/www/moodle/33x/lib/moodlelib.php(7760): call_user_func_array('mod_hvp\\privacy...', Array)
- #4 /var/www/moodle/33x/privacy/classes/manager.php(495): component_class_callback('mod_hvp\\privacy...', 'get_contexts_fo...', Array)
- #5 /var/www/moodle/33x/privacy/classes/manager.php(528): core_privacy\manager::component_class_callback('mod_hvp', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
- #6 /var/www/moodle/33x/privacy/classes/manager.php(237): core_privacy\manager->handled_component_class_callback('mod_hvp', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
- #7 /var/www/moodle/33x/admin/tool/dataprivacy/classes/task/initiate_data_request_task.php(102): core_privacy\manager->get_contexts_for_userid('117')
- #8 /var/www/moodle/33x/lib/cronlib.php(156): tool_dataprivacy\task\initiate_data_request_task->execute()
- #9 /var/www/moodle/33x/lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\initiate_data_request_task))
- #10 /var/www/moodle/33x/admin/cli/cron.php(61): cron_run()
- #11 {main}

**Comment by Jarvil** [comment]
@thomasmars

**Comment by Jarvil** [comment]
@falcon-git

**Comment by fnoks** [comment]
I am sorry about this one not being handled very well. I have created an issue to fix this bug:
https://h5ptechnology.atlassian.net/browse/HFP-2152

**Comment by thomasmars** [comment]
@Jarvil I have fixed this and released version 1.10 of the H5P plugin for Moodle.
Thanks for reporting this 🥇
