### ISSUE TITLE
Error when duplicating activity

### ISSUE THREAD

**Issue by tobiasreischmann** [h5p/h5p-moodle-plugin#211]
It is currently not possible to duplicate an activity. I suppose that the backup_hvp_stepslib.php is based on an old database schema (see https://github.com/h5p/h5p-moodle-plugin/blob/973e4833b4b9b2efb7dddb0afddf524e88648142/backup/moodle2/backup_hvp_stepslib.php#L94-L103). The database table _mdl_hvp_ no longer contains _h.meta_keywords_, _h.meta_description_. Additionally, _h.author_ is now _h.authors_.

**Comment by fnoks** [comment]
Are you running Moodle from github? If so, you should now master is the "unstable" branch, and I hope you are not using that in a production environment.

But thanks for letting us know - we will fix this for the upcoming release.

**Comment by fnoks** [comment]
I have created an issue for this here: https://h5ptechnology.atlassian.net/browse/HFP-2162
