### ISSUE TITLE
Fails to deploy to Totara environments due to invalid install.xml file

### ISSUE THREAD

**Issue by danmarsden** [h5p/h5p-moodle-plugin#216]
it looks like your install.xml file has been edited by hand instead of using the Moodle XMLDB tool so is generating invalid xml. This works fine on Moodle sites because the install.xml is not validated in the same way, but Totara includes a unit test which checks for valid install.xml files which is run before our continuous integration processes will allow a site deploy.

To fix this you can use the XMLDB tool (admin > development > XMLDB) "Load" the mod/hvp install.xml file, make a change to the description of one of the tables (add a full stop or something) and XMLDB will be see a change and allow you to re-save it. Re-saving the file will update the invalid xml and generate a correct updated version of the file.

If you would prefer to manage a pull request, I'll add one here that you can use to remove the invalid xml values.

**Comment by fnoks** [comment]
If you could create a Pull Request, that would be great (and this issue will be much faster resolved)
