### ISSUE TITLE
Adding an H5P resource on Moodle 3.5

### ISSUE THREAD

**Issue by Edunao** [h5p/h5p-moodle-plugin#221]
Hi,
I have an issue while adding an H5P resource on Moodle : 
When I select "Course presentation" the resource starts the upload with no end.
When I select "Multiple choice", after filling the fields and saving i get this message : 

Exception : Call to a member function get_content() on boolean
Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 258 of /mod/hvp/classes/file_storage.php: Error thrown
line 2124 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\file_storage->cacheAssets()
line 183 of /mod/hvp/classes/view_assets.php: call to H5PCore->getDependenciesFiles()
line 82 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getdependencyfiles()
line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()

Thanks in advance.

**Comment by thomasmars** [comment]
Hi,
Can you go to your config.php and add this line:
`$CFG->mod_hvp_aggregate_assets`
This will turn of aggregation of your assets. Then try to enter the page again to see if you get a different error.
Most likely the upload of your library files went wrong and you're missing some files, this can be solved by uploading the libraries again.

**Comment by Edunao** [comment]
Hi,
We added the line $CFG->mod_hvp_aggregate_assets =0
When I select "Course presentation" the resource starts the upload with no end.
When I select "Multiple choice", after filling the fields and saving i just get an empty H5P resource ( you can only see the titles of the resource)
![capture d ecran 2018-09-04 a 15 28 17](https://user-images.githubusercontent.com/22300677/45035134-8ed98c80-b059-11e8-994a-810aaeee69f9.png)

**Comment by thomasmars** [comment]
Please check your browser's console and your php error log for any errors.

**Comment by Edunao** [comment]
Hi,

When I select "Multiple Choice", after filling the fields and saving i get this error " Exception : Call to a member function get_content() on boolean". I checked my browser's console and php error log as you asked and this is what i get :
![h5p_multiple_choice](https://user-images.githubusercontent.com/22300677/45819123-dca1f600-bce3-11e8-9888-f680c30d6507.png)
When I select "Course Presentation" the resource starts the upload with no end. This is what i get in my browser's console and php error log : 
![h5p_course_presentation](https://user-images.githubusercontent.com/22300677/45819168-fd6a4b80-bce3-11e8-9a20-ccb1ad6f3fb8.png)

Down bellow the php error log : 

* line 2124 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\file_storage->cacheAssets()
* line 183 of /mod/hvp/classes/view_assets.php: call to H5PCore->getDependenciesFiles()
* line 82 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getdependencyfiles()
* line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()" while reading response header from upstream, client: 82.226.210.64, server: k2preprod-2018-2019.edunao.edu, request: "GET /mod/hvp/view.php?id=407314 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-edunaov2.sock:", host: "k2preprod.edunao.edu", referrer: "https://k2preprod.edunao.edu/mod/hvp/view.php?id=407314"
2018/09/20 12:40:36 [error] 46166#46166: *413301 FastCGI sent in stderr: "PHP message: Default exception handler: Can not serve file - server configuration problem. Debug: Could not retrieve the requested file, check your file permissions.
Error code: cannotservefile
* line 363 of /mod/hvp/classes/file_storage.php: file_serving_exception thrown
* line 373 of /mod/hvp/editor/h5peditor.class.php: call to mod_hvp\file_storage->getContent()
* line 89 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5peditor->getLibraryData()
* line 232 of /mod/hvp/ajax.php: call to H5PEditorAjax->action()" while reading response header from upstream, client: 82.226.210.64, server: k2preprod-2018-2019.edunao.edu, request: "GET /mod/hvp/ajax.php?contextId=443086&token=96e3a8c208444&action=libraries&machineName=H5P.CoursePresentation&majorVersion=1&minorVersion=16 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-edunaov2.sock:", host: "k2preprod.edunao.edu", referrer: "https://k2preprod.edunao.edu/course/modedit.php?add=hvp&type=&course=12262&section=1&return=0&sr=1"

**Comment by thomasmars** [comment]
Hi,
The plugin is not able to find your library files, something must have gone wrong while installing the libraries.
Please do the following in order to reinstall libraries:

1) Set the following in your config:
`$CFG->mod_hvp_dev = true;`
2) Download the official multiple choice example from h5p.org: https://h5p.org/multichoice
3) Upload the downloaded library in step 2 to your moodle site through the H5P editor
4) Make sure that there are no errors when uploading it.
5) Check that the content works properly after uploading it
6) Remove the line from step 1 from your config.php

Repeat for Course Presentation. This should make sure that all libraries used for Multiple Choice and Course Presentation are reinstalled and in a working state.
Let us know if you run into any further troubles after performing these  steps.

**Comment by Edunao** [comment]
Hi,

We did what you asked us and while adding and H5P resource, this is the error we have in our browser's console : 
![capture_1](https://user-images.githubusercontent.com/22300677/46005624-f95c7600-c0b5-11e8-8974-7cf726954b92.png)
![capture_2](https://user-images.githubusercontent.com/22300677/46005629-fa8da300-c0b5-11e8-886a-bfc3610e52a7.png)

Thank you in advance

**Comment by thomasmars** [comment]
Do you get any PHP errors when you try to upload the file ?

**Comment by Edunao** [comment]
No we didn't have any php error

**Comment by thomasmars** [comment]
Looks like it is a server configuration or file storage issue. Please make sure that your server has permission to store and retrieve files. Also make sure that you've followed the Moodle instructions for configuring your server at: https://docs.moodle.org/35/en/Installing_Moodle
