### ISSUE TITLE
Essay Grading

### ISSUE THREAD

**Issue by jonfila** [h5p/h5p-moodle-plugin#224]
The grades for the Essay module are not being entered into the gradebook automatically.

There are also two problems I'm seeing with how to get to student work.
1. You have to click on the gradebook and then click on the link to the Essay module to see the course report load.
2. When you click on one of those reports for a user nothing loads so I cannot as a teacher, view student responses.

Even if I could view it, I would have to go to the gradebook, click on the Essay link, click on the report and then go back into the gradebook to enter the score which is a few more clicks. I would like to see the user interface work the same way as it does for other Moodle assignments. Can't the grade simply be entered from the report page and saved? I would also like to know which assignments have been submitted and which have not. From the report, it isn't clear.
<img width="1064" alt="screen shot 2018-10-10 at 10 42 13 am" src="https://user-images.githubusercontent.com/8570031/46748504-5856e900-cc79-11e8-8584-fd89191eb349.png">
<img width="1064" alt="screen shot 2018-10-10 at 10 42 27 am" src="https://user-images.githubusercontent.com/8570031/46748520-5ee56080-cc79-11e8-8889-5a0c0916ce0d.png">
There is nothing to display here when I click on Report.

**Comment by otacke** [comment]
You may be pleased to learn that the required functionality has been added to Essay quite some time ago, but there's still a peer review that's open. https://h5ptechnology.atlassian.net/browse/HFP-1879
Not sure about possible improvements in the moodle plugin though.

**Comment by thomasmars** [comment]
Closing this as it related to the essay content type and reporting module, rather than the h5p moodle integration.
