### ISSUE TITLE
Wrong access to library properties in editor_framework#getLibraries

### ISSUE THREAD

**Issue by sb-relaxt-at** [h5p/h5p-moodle-plugin#229]
There is an issue with the changes introduced in ["Rename metadata to metadata_settings"](https://github.com/h5p/h5p-moodle-plugin/commit/df4bb9c04d9df7567bebbd0ba0febcfaa2967de2). In [editor_framework#getLibraries](https://github.com/h5p/h5p-moodle-plugin/blob/stable/classes/editor_framework.php#L152) there are case sensitive field aliases used for metadata_settings (metadataSettings), major_version (majorVersion) and so on. The used method [get_records_sql](https://github.com/moodle/moodle/blob/master/lib/dml/mysqli_native_moodle_database.php#L1250) automatically transforms the resulting array to lower case keys, therefore it cannot be accessed as `$library->metadataSettings`, but as `$library->metadatasettings`. 

This bug became only visible if PHP notices are shown and if NOT using the hub. When adding an new activity the normal type selection dropdown cannot be rendered ("Error, unable to load libraries.") as the call to the `ajax.php` does not return a valid json (due to the notices in the response).

**Comment by thomasmars** [comment]
Thanks for reporting this. It was fixed in https://github.com/h5p/h5p-moodle-plugin/commit/dcba1004f52579af78f7324496c33197a1c46ecb.
