### ISSUE TITLE
Course presentation comment-field alignment problems with Internet Explorer 11

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#233]
Hello,

There is a bug in Course presentation comment-field alignment with Internet Explorer 11. See attached video.

This appears only when you have first created f.ex. multiplechoice question in course presentation -> saved the question -> and when you go to edit it again.

When you are back editing and add text to the comment-field -> select it -> click the link icon -> the pop up opens to the right part of the screen and you cannot even see/use it. This with Moodles Clean theme.

If you now, with this pop-up open, scroll browser vertical scrollbar to the top of the page you can now see the editor fine since it moves to the top left of the h5p editor. If you then move it back down it goes to the right and is non editable.

tested with Moodle 3.5.3, mod_hvp 1.12, moodle theme Clean.

Steps to repeat:

1. Create course presentation
2. add multiple choice question -> choose done
3. now edit the multiple choice question with Internet Explorer 11
4. Go comment-field -> type something -> choose text -> click link icon -> notice how the alignment is wrong

Problem with Clean theme:
[comment.zip](https://github.com/h5p/h5p-moodle-plugin/files/2610035/comment.zip)

**Comment by thomasmars** [comment]
Hi, this is a Course Presentation, not a H5P moodle plugin specific issue, please open this issue in the [course presentation repository](https://github.com/h5p/h5p-course-presentation) instead, thanks.
