### ISSUE TITLE
Column 'json_content' cannot be null

### ISSUE THREAD

**Issue by szyper-sakrona** [h5p/h5p-moodle-plugin#234]
After last upgrade to 1.13 our moodle system (v.3.2.3, mariadb, apache) we're unable to save/insert changes to any H5P content. The error is:
Cannot write to database...

Debug error:
Debug info: Column 'json_content' cannot be null
UPDATE mdl_hvp SET authors = ?,changes = ?,source = ?,license = ?,license_version = ?,license_extras = ?,author_comments = ?,year_from = ?,year_to = ?,name = ?,course = ?,intro = ?,introformat = ?,json_content = ?,embed_type = ?,main_library_id = ?,filtered = ?,disable = ?,timemodified = ? WHERE id=?
[array (
0 => NULL,
1 => NULL,
2 => NULL,
3 => NULL,
4 => NULL,
5 => NULL,
6 => NULL,
7 => NULL,
8 => NULL,
9 => 'Fiszki - pojęcia podstawowe',
10 => '198',
11 => '',
12 => '1',
13 => NULL,
14 => 'div',
15 => '200',
16 => '',
17 => 0,
18 => 1543230379,
19 => '798',
)]
Error code: dmlwriteexception
Stack trace:

    line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 1487 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1519 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->update_record_raw()
    line 946 of /mod/hvp/classes/framework.php: call to mysqli_native_moodle_database->update_record()
    line 1936 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->updateContent()
    line 147 of /mod/hvp/lib.php: call to H5PCore->saveContent()
    line 109 of /mod/hvp/lib.php: call to hvp_save_content()
    line 571 of /course/modlib.php: call to hvp_update_instance()
    line 159 of /course/modedit.php: call to update_moduleinfo()

Output buffer: <br /> <b>Notice</b>: Undefined index: metadata in <b>/var/www/html/moodle/mod/hvp/classes/framework.php</b> on line <b>926</b><br /> <br /> <b>Notice</b>: Undefined index: params in <b>/var/www/html/moodle/mod/hvp/classes/framework.php</b> on line <b>931</b><br /> 
-----------------------------------------------------------------------------------------------------------

Temporary my solution was to remove json_content from update query - then it works and write changes.

**Comment by icc** [comment]
This has been fixed for all but 3.2. Please see #241 and a possible fix for 3.2 here: https://h5p.org/comment/24444#comment-24444

**Comment by logan-reynolds** [comment]
I'm seeing this same error regarding null json_content on Totara 11.9 when testing mod_hvp 2018113000 release 1.14:
```
Debug info: Column 'json_content' cannot be null
INSERT INTO mdl_hvp ("authors","changes","source","license","license_version","license_extras","author_comments","year_from","year_to","name","course","intro","introformat","json_content","embed_type","main_library_id","filtered","disable","timemodified","slug","timecreated") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => NULL,
1 => NULL,
2 => NULL,
3 => NULL,
4 => NULL,
5 => NULL,
6 => NULL,
7 => NULL,
8 => NULL,
9 => 'testhvp',
10 => '3',
11 => '<p>testhvp<br></p>',
12 => '1',
13 => NULL,
14 => 'div',
15 => '2',
16 => '',
17 => 0,
18 => 1549567064,
19 => '',
20 => 1549567064,
)]
Error code: dmlwriteexception
Stack trace:

    line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 1233 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1279 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 943 of /mod/hvp/classes/framework.php: call to mysqli_native_moodle_database->insert_record()
    line 970 of /mod/hvp/classes/framework.php: call to mod_hvp\framework->updateContent()
    line 1939 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->insertContent()
    line 147 of /mod/hvp/lib.php: call to H5PCore->saveContent()
    line 86 of /mod/hvp/lib.php: call to hvp_save_content()
    line 121 of /course/modlib.php: call to hvp_add_instance()
    line 176 of /course/modedit.php: call to add_moduleinfo()

Output buffer: <br /> <b>Notice</b>: Undefined index: metadata in <b>/var/www/html/TOTARA_110_STABLE/mod/hvp/classes/framework.php</b> on line <b>926</b><br /> <br /> <b>Notice</b>: Undefined index: params in <b>/var/www/html/TOTARA_110_STABLE/mod/hvp/classes/framework.php</b> on line <b>931</b><br />
```

**Comment by icc** [comment]
@logan-reynolds This is fixed in the next release of the plugin. If you want to make it work right away you can download and replace this [mod_form.php](https://raw.githubusercontent.com/h5p/h5p-moodle-plugin/6e39145f5c81a1064ea91e8db5e406e6a7c1e545/mod_form.php) and replace the one in your `mod/hvp/` folder.
