### ISSUE TITLE
How to manually update H5P-libraries in Moodle?

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#235]
Hello,

How can I manully update H5P libraries in Moodle when I don't have access to H5P hub -feature (restricted connectivity to public internet on this server)?

**Comment by icc** [comment]
You should be able to do this by uploading H5P files through the form at `/mod/hvp/library_list.php`

**Comment by Jarvil** [comment]
Hello,

Thanks, where can I download a signle H5P-file that can update all libraries at once?

**Comment by icc** [comment]
Unfortunately, there is no such file. But what you can do is create a Column on h5p.org which includes all the content types you'd like to have and then Download it and upload it to your Libraries Form.

**Comment by Jarvil** [comment]
Hello,

ok thanks for the tip.
