### ISSUE TITLE
This page did not call $PAGE->set_url(...).

### ISSUE THREAD

**Issue by imarichev** [h5p/h5p-moodle-plugin#238]
Hi,

I keep getting error "This page did not call $PAGE->set_url(...)." on course module pages with H5P.
It seems strange, that I can't find any notes about this error from other users.
I know how to handle it (just move $PAGE->set_url() higher in the main plugin file), but then I will need to do it everytime after updates. 
Can you do it, please?
Or, maybe, I should do it myself and create a pull request?
Thank you.

**Comment by thomasmars** [comment]
Please specify the exact version of Moodle, PHP, themes, etc you are using and how you are able to reproduce this error on course module pages with H5P.
I'm not able to reproduce the error with Moodle 3.6.1, PHP 7.1 and H5P 1.14.

**Comment by imarichev** [comment]
Moodle 3.1.11
php 5.6.37
h5p 2018113000 build
This error appeared on every course module page with H5P on it.
As far as I understand Moodle requires to call $PAGE->set_url() before any output on the page. So it may be fixed by moving this method call a little bit higher in view.php code.
![error](https://user-images.githubusercontent.com/22023804/50881365-6a6c3300-13f2-11e9-8e06-144e58751cad.png)

**Comment by thomasmars** [comment]
We're not able to reproduce this. Please reopen with additional info on how to reproduce it if it is still happening.
