### ISSUE TITLE
Editor fails with type error in h5peditor-group.js

### ISSUE THREAD

**Issue by rochelmeyer** [h5p/h5p-moodle-plugin#240]
Good morning, 
moodle 3.5 with h5p-Plugin Ver. 1.14 /Firefox 64, Linux

Editor fails with this console output: 
TypeError: field is undefined h5peditor-group.js:14:3

Thanks for taking care!

**Comment by thomasmars** [comment]
Please give some more information/context and detailed steps to reproduce this. 
E.g.:
# Detailed steps to reproduce the bug (exactly how and when did it happen)
# H5P content type and version (if a content type was used), and a sample URL or attached H5P.
# Any PHP errors
# Screenshots if it's a visual problem

What did you do before this happened ? Is it a fresh install of the H5P plugin or did this start happening after an update ?

**Comment by rochelmeyer** [comment]
Sorry, my fault. There was some older stuff left in the browser cache. Refreshing the cache solved the issue. 
Thanks anyway!

**Comment by rochelmeyer** [comment]
I see an issue like the one from above again, despite of refreshing all caches. This happens in a H5P-activity i created a while ago. When trying to edit that, the editor is not being loaded (just says: "Loading, please wait ..."). 

From the Browser console: 
TypeError: libraries.libraries is undefined h5peditor-selector-hub.js:18:21
    getContentType https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-selector-hub.js?ver=2019031301:18
    SelectorHub https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-selector-hub.js?ver=2019031301:36
    LibrarySelector https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-library-selector.js?ver=2019031301:42
    load https://somewebsitesite.de/moodle/mod/hvp/editor/scripts/h5peditor-editor.js?ver=2019031301:140
    jQuery 4

I see no PHP errors. Latest and up to date Moodle 3.6, most recent hvp from git. 

Trying to set up a new H5P-Activity: 
TypeError: "e.libraries is undefined"
    r https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:29
    t https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:24
    constructClassInstance https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    beginWork https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    a https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    s https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    c https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    y https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    h https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    updateContainer https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    pt https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    unbatchedUpdates https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    pt https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    render https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    u https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    e https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5p-hub-client.js?ver=2019031301:17
    SelectorHub https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-selector-hub.js?ver=2019031301:42
    LibrarySelector https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-library-selector.js?ver=2019031301:42
    load https://somewebsite.de/moodle/mod/hvp/editor/scripts/h5peditor-editor.js?ver=2019031301:140
    jQuery 4
h5p-hub-client.js:17:45394

Again: No PHP Errors

Thanks

**Comment by thomasmars** [comment]
Please set `$CFG->mod_hvp_dev = '1';` in your config, and try to re-upload the library that you're trying to edit from the [examples and downloads page](https://h5p.org/content-types-and-applications). Check if there are any PHP errors while re-installing the libraries.

**Comment by rochelmeyer** [comment]
Resolved: H5P seems to need "git submodule update --init" after pulling the code. I missed that step.
