### ISSUE TITLE
add an activity in Moodle 3.2 fails with latest update

### ISSUE THREAD

**Issue by danielavetica** [h5p/h5p-moodle-plugin#241]
I just updated a Moodle 3.2 environment with the latest H5P release (version 2018113000). 
when on a coursepage, I try to add an H5P activity,( accordeon).
I get this error message:

> Debug info: Column 'json_content' cannot be null
> INSERT INTO mdl_hvp (authors,changes,source,license,license_version,license_extras,author_comments,year_from,year_to,name,course,intro,introformat,json_content,embed_type,main_library_id,filtered,disable,timemodified,slug,timecreated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
> [array (
> 0 => NULL,
> 1 => NULL,
> 2 => NULL,
> 3 => NULL,
> 4 => NULL,
> 5 => NULL,
> 6 => NULL,
> 7 => NULL,
> 8 => NULL,
> 9 => 'title',
> 10 => '1047',
> 11 => '<p>test</p>',
> 12 => '1',
> 13 => NULL,
> 14 => 'div',
> 15 => '9',
> 16 => '',
> 17 => 0,
> 18 => 1546951200,
> 19 => '',
> 20 => 1546951200,
> )]
> Error code: dmlwriteexception

Got the same error on multiple 3.2 sites with latest H5P plugin. 
Moodle 3.5 environments does not give this issue.

Can you check this please?

With kind regards,
Daniel Dubbeldam

**Comment by danielavetica** [comment]
associated stack trace:

Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 943 of /mod/hvp/classes/framework.php: call to mysqli_native_moodle_database->insert_record()
line 970 of /mod/hvp/classes/framework.php: call to mod_hvp\framework->updateContent()
line 1939 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->insertContent()
line 147 of /mod/hvp/lib.php: call to H5PCore->saveContent()
line 86 of /mod/hvp/lib.php: call to hvp_save_content()
line 121 of /course/modlib.php: call to hvp_add_instance()
line 161 of /course/modedit.php: call to add_moduleinfo()

**Comment by danowar2k** [comment]
We've stumbled upon this bug when updating hvp to v1.13.

We have Moodle 3.2.7 running. 
The Moodle Plugin site says 1.13 works with Moodle 3.2:
https://moodle.org/plugins/pluginversion.php?id=18324

However, hvp 1.13 and up uses a moodleform callback function called "data_postprocessing" which simply doesn't exist yet in Moodle 3.2. See these lines in the Moodle changelog:
https://github.com/moodle/moodle/blob/6e445671c1679e43796bced77f0a52f79590c80d/mod/upgrade.txt#L40-L62

The corresponding lines in the hvp mod_form.php:
https://github.com/h5p/h5p-moodle-plugin/blob/f00824d40f7510d45ee780e8aa4da710da11a6b6/mod_form.php#L323-L363

So, you have to either correct the hvp requirements to at least Moodle 3.3 or find another method to use, it seems.

**Comment by thomasmars** [comment]
This was fixed in https://github.com/h5p/h5p-moodle-plugin/commit/1b83a02842b2af65bfaaa54549ccdcfd73bc23c3
