### ISSUE TITLE
mod_form version check breaks compatibility with Totara Learn 12

### ISSUE THREAD

**Issue by andreyamin** [h5p/h5p-moodle-plugin#242]
Hi all,

Looks like the version check [here](https://github.com/h5p/h5p-moodle-plugin/blob/f00824d40f7510d45ee780e8aa4da710da11a6b6/mod_form.php#L378) added to provide compatibility with prior to Moodle 3.2 breaks compatibility with Totara Learn 12. Would be great if we can change this check so that the plugin could work with Totara.

**Comment by danmarsden** [comment]
I've just filed a pull request here with a possible solution. I've tested this on Moodle master and Totara 12 and both seem to work ok - might be a good idea for someone else to test this as well (make sure you post which versions you have tested with.)

Ideally we'd need to test:
Moodle versions prior to 3.2
Newer Moodle versions.
Totara 12 and others.

**Comment by andreyamin** [comment]
You're a legend @danmarsden. Checking for the method instead of the version makes perfect sense.
I've tested this on Moodle 3.1 onwards and Totara 2.9 up to evergreen.
+1 from Totara.

**Comment by andreyamin** [comment]
@thomasmars please let me know if you need anything from Totara on this.
