### ISSUE TITLE
Course presentation slow to load when first accessed

### ISSUE THREAD

**Issue by philrankinBB** [h5p/h5p-moodle-plugin#244]
*DESCRIPTION*
Course presentation content type in H5P causes slow loading the first time the activity page is loaded (~30 seconds)

*STEPS TO REPLICATE*
1. Go to a test course>Add an activity>Interactive content
2. From the content types select 'Course presentation' (leave other settings default)
3. Click 'Save and display'

*OBSERVED BEHAVIOUR*
Page takes approx 30 seconds to load the first time. Subsequent loads are much faster.

*PLUGIN VERSION*
1.12 2018110600

**Comment by thomasmars** [comment]
This is expected if you're on a slow network, the first time you load resources you have to get all the assets/resources, both code and media. Subsequent loads are much faster because resources have been cached.

**Comment by philrankinBB** [comment]
This was tested on a 100mbs down/40mbps up connection, so I don't think the connection speed is the problem. It occurs when the course presentation is completely empty and no additional media has been added. Given the connection speed and time taken to load it would mean that an empty course presentation is 300MB in size. If that's the case then so be it. If not, I really think this deserves more attention.

**Comment by icc** [comment]
This is could be related to Moodle's custom file system. Is your data directory stored on the same server as the rest of the code? If so, I fair that only a faster disk + CPU will be able to speed this up. 
Alternatively, completely disabling the H5P download button may fix the issue as well.

**Comment by thomasmars** [comment]
The performance is greatly affected by the speed of your server, both network and processing power and
bandwidth between you and the server.

Running your steps on my local machine takes about 5 seconds. I ran xdebug profiler, which reveals that most of the time is spent moving files, zip operations and in db operations.
The first time you save content you will create an export file, which has to be built.
You can disable this by disabling export if you wish to save some seconds.
The rest of the time is used to process the content, content validation, building the dependency tree and making sure that content is moved to the appropriate place using the moodle file api, which are all necessary operations.

I would start by looking at the performance and network bandwidth of the server if the speed is too slow for you. Also you may have some other plugins that may be slowing down the storage. I would also be happy to see some performance profiling for the reproducible steps if you think H5P is doing something strange. Don't hesitate to let us know if you find something. Thanks

**Comment by philrankinBB** [comment]
Hi All, thanks for the support on this one. Turns out it was related to excessive AWS API calls used to move files around. The only way to fix it was to disable the download button.

**Comment by thomasmars** [comment]
If you wish to make the integration work better with AWS you can implement the H5PFileStorage interface for AWS, or override the functions from classes/file_storage(). This should give you full control over how and when files are moved around, and you can change the file storing from using the Moodle API, to using for instance the AWS SDK, which should let you do bulk file operations for instance.
