### ISSUE TITLE
Totara coursecatalog courses icon appearing larger than other icons

### ISSUE THREAD

**Issue by dezglidden** [h5p/h5p-moodle-plugin#247]
In Totara, the /totara/coursecatalog/courses.php page is displaying the icon larger than expected. Other icons are inserted as spans with font awesome classes whereas the h5p icon is an image. See attached example where I've added styles in the inspector on the top row and how it is actually displayed on the bottom row

![h5p](https://user-images.githubusercontent.com/3153742/52476777-a3392c80-2b97-11e9-99f5-12a8bf3785ae.png)

Theme tested on: Basis (core)
Browser: Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by thomasmars** [comment]
I have created an issue for fixing this at: https://h5ptechnology.atlassian.net/browse/HFP-2670

**Comment by thomasmars** [comment]
Will be handled in #254
