### ISSUE TITLE
Apache error log - SQL select problem

### ISSUE THREAD

**Issue by miotto** [h5p/h5p-moodle-plugin#249]
1. Activate the debug settings in Moodle
2. Create an h5p activity "Multiple Choice" and save it.
3. Change the content type to "Interactive Video".

Then the error appears in the Apache log:
`
[Thu Feb 14 10:06:46.891173 2019] [php7:notice] [pid 3185] [client 192.168.56.1:59186] Default exception handler: Datensatz kann nicht in der Datenbanktabelle context gefunden werden Debug: SELECT * FROM {context} WHERE id = ?\n[array (\n  0 => '326',\n)]\nError code: invalidrecord\n* line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown\n* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()\n* line 5077 of /lib/accesslib.php: call to moodle_database->get_record()\n* line 94 of /mod/hvp/classes/content_user_data.php: call to context::instance_by_id()\n* line 65 of /mod/hvp/classes/content_user_data.php: call to mod_hvp\\content_user_data::store_data()\n* line 45 of /mod/hvp/ajax.php: call to mod_hvp\\content_user_data::handle_ajax()\n, referer: https://192.168.56.131/moodle/course/modedit.php?update=326&return=0&sr=0
`

The `store_data` function in the `classes/content_user_data.php` file tries to get the module ID from the context table (line 93). In my opinion, it would have to be the table course_modules.

**Comment by thomasmars** [comment]
I assume this was happening because Interactive Video was sending xAPI completion events from the editor. I'm not able to reproduce this with the latest version of Interactive Video, please open with some more detailed steps if you're still able to reproduce this with the latest version of Interactive Video.
