### ISSUE TITLE
Quiz correct answers are shared in html page content (H5P "Fill in the Blanks") 

### ISSUE THREAD

**Issue by z9zaharov** [h5p/h5p-moodle-plugin#252]
It seems that there is a hack which allows quiz participants to get correct answers during passing a test. It could be even reproduced on demo site.

1) Step 1.[Quiz page](https://h5p.org/sites/default/files/h5p_hack1.png)
2) Click "Ctrl+U" to see page content. And look for the anchor text.
[Quiz plain html content page](https://h5p.org/sites/default/files/h5p_hack2.png)

**Comment by icc** [comment]
That is correct and I think it's very clearly stated that this is possible in both the documentation and the description of the plugin:
> Note that it is currently possible for people with programming skills to cheat in H5P interactions and obtain the full score without knowing the correct answers. H5Ps must not be used for exams or similar.

But do note that bakend evaluation of answers are coming in a future update, ref. [Roadmap](https://h5p.org/roadmap).
