### ISSUE TITLE
Backup / restore is slow in Moodle

### ISSUE THREAD

**Issue by gemguardian** [h5p/h5p-moodle-plugin#253]
I was not sure what the best approach is - reopening an issue or creating a new one since this is a known problem even though it is not the recycle bin this time. 

We noticed more and more issues while using backup / restore course function in Moodle with course that contain H5P modules. The process is very slow, and sometimes even "eats" up all the server capacity. 

I noticed that there is a fix suggestion in: https://h5ptechnology.atlassian.net/browse/HFP-839
And after applying this the backup / restore process is improved. Though I am wondering why this should not be fixed in the module itself. 

is there any use that H5P takes in the libraries? 

See for related trackers: 
- https://h5ptechnology.atlassian.net/browse/HFP-839
- https://github.com/h5p/h5p-moodle-plugin/issues/138

**Comment by thomasmars** [comment]
If you're restoring to a site that does not already have the libraries, the libraries must be backed up so that the site is able to restore the content. This is why the libraries are backed up by default.
A possible improvement would be to make the "mod_hvp_backup_libraries" option configurable in the UI, instead of having to set it in code, thus the admin could more easily choose to disable the option for backing up the libraries, but for now this is not a big priority as this already is configurable for those who desires it.

**Comment by gemguardian** [comment]
Hi Thomas,

Thank you for the explanation. It makes a lot of sense this way.

I like your idea of a UI setting for siteadministrators.
Since not every site administrator have the option ór the capability to make the change in de config.php file that is required now.

I know there is a project where h5p are working for an integration in Moodle. So it makes it kind of difficult for me to make an assessment on if an investment to get this setting is worth. Is there any insight on this subject that you might be able to share?

Gem




Van: Thomas <notifications@github.com>
Verzonden: Wednesday, March 13, 2019 11:30
Aan: h5p/h5p-moodle-plugin <h5p-moodle-plugin@noreply.github.com>
CC: Gemma Lesterhuis <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [h5p/h5p-moodle-plugin] Backup / restore is slow in Moodle (#253)


If you're restoring to a site that does not already have the libraries, the libraries must be backed up so that the site is able to restore the content. This is why the libraries are backed up by default.
A possible improvement would be to make the "mod_hvp_backup_libraries" option configurable in the UI, instead of having to set it in code, thus the admin could more easily choose to disable the option for backing up the libraries, but for now this is not a big priority as this already is configurable for those who desires it.

**Comment by relecand** [comment]
Problem of slow backups solved with this PR: https://github.com/h5p/moodle-mod_hvp/pull/588
