### ISSUE TITLE
Icon size in Recently accessed courses block

### ISSUE THREAD

**Issue by andurif** [h5p/h5p-moodle-plugin#254]
Hello,
In the new Recently accessed courses block added in moodle 3.6 the H5P icon mod is displayed bigger than others icon mods. This has an impact on the block size. Maybe this issue is the same or can be related to the [#247](https://github.com/h5p/h5p-moodle-plugin/issues/247) issue.

Here some attached examples to compare two displays:
![image](https://user-images.githubusercontent.com/36671916/53481606-e04d5c00-3a7d-11e9-94a8-f9fce97fbd2f.png) 
![image](https://user-images.githubusercontent.com/36671916/53481637-ecd1b480-3a7d-11e9-8c21-7781e8c2814f.png)

**Comment by thomasmars** [comment]
Hi,
Thanks for reporting this, I have created an issue for fixing it at: https://h5ptechnology.atlassian.net/browse/HFP-2670

**Comment by golenkovm** [comment]
Hi H5P team,
Could you have a look at my PR regarding this issue?
Thanks,
Mikhail

**Comment by thomasmars** [comment]
Thanks :+1:
