### ISSUE TITLE
Results page in Moodle not displaying data

### ISSUE THREAD

**Issue by haietza** [h5p/h5p-moodle-plugin#255]
We have the H5P plugin installed on Moodle and are testing the Course Presentation type with a Summary. The grade for a user does appear in the gradebook, but when you click on the activity to go to the Results page, no data is displayed for Score, Maximum Score, or Finished. When you click on the Report link, you can view the individual student's responses, but none of that data is displaying in the table on the Results page. It looks like an issue with the JS that fetches the data?

**Comment by haietza** [comment]
Also receive this error when viewing the report page and purge the caches: 

[07-Mar-2019 08:07:43 America/New_York] Debugging: You need to update your sql to include additional name fields in the user object. in 
* line 3463 of /lib/moodlelib.php: call to debugging()
* line 133 of /mod/hvp/classes/results.php: call to fullname()
* line 106 of /mod/hvp/classes/results.php: call to mod_hvp\results->get_human_readable_results()
* line 208 of /mod/hvp/ajax.php: call to mod_hvp\results->print_results()

[07-Mar-2019 08:07:50 America/New_York] Default exception handler: Invalid course module ID Debug: 
Error code: invalidcoursemodule
* line 494 of /lib/setuplib.php: moodle_exception thrown
* line 33 of /mod/hvp/grade.php: call to print_error()

**Comment by nadavkav** [comment]
I am experiencing the same issue.

Also, clicking a few times on the column sort icons, I get to see the grades of the first student duplicated onto all the other students. weird.

**Comment by nadavkav** [comment]
Suggested pull request seems to solve this issue
https://github.com/h5p/h5p-moodle-plugin/pull/257
Please review.

**Comment by thomasmars** [comment]
Thanks for the info. Should be fixed in https://github.com/h5p/h5p-moodle-plugin/commit/24cdadda0769bb03ef161414174b81689f639f72.
Please let us know if this fixes it properly for you. The fix will be part of an hotfix for the plugin.

**Comment by haietza** [comment]
@thomasmars Yes this appears to have fixed the issue. Thanks so much for the quick response and fix!

**Comment by thomasmars** [comment]
Version 1.17 has now been officially released with the fix. Please make sure to update.

**Comment by nadavkav** [comment]
Thank you @thomasmars for the quick response and fix
