### ISSUE TITLE
Add hook/event to alter semantics

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#26]
Makes it easier for other plugins to alter or modify the library semantics.
Implement `alterLibrarySemantics()` in `hvp.php`.

[WordPress plugin's alterLibrarySemantics()](https://github.com/h5p/h5p-wordpress-plugin/blob/master/public/class-h5p-wordpress.php#L584)

**Comment by nadavkav** [comment]
+1

**Comment by thomasmars** [comment]
Solved in https://github.com/h5p/h5p-moodle-plugin/commit/4225a97ce827fa6a1b86659085a1cd1166610ff5

**Comment by nadavkav** [comment]
Yesssss :smile:
