### ISSUE TITLE
Backup (and restore) is extremely slow

### ISSUE THREAD

**Issue by Kathrin84** [h5p/h5p-moodle-plugin#262]
Hi,

we've encountered that the backup and restore process for the H5P activity is extremely slow. Backing up a single H5P instance containing only a MC question type takes about 10 minutes to be processed.
I've tested several instances of the activity on several Moodle instances (own server and Docker instances - Moodle in the version 3.6+). The behavior was the same on each of them.

I don't know what could take so long, especially as the instances were tiny and not much content was added to the H5P instance...

Does anyone else observed this problem, too? I would appreciate if you could have a look at this.

Thanks and best,
Kathrin

**Comment by gemguardian** [comment]
Kathrin 
See: https://github.com/h5p/h5p-moodle-plugin/issues/253

Gemma

**Comment by relecand** [comment]
Problem of slow backups solved with this PR: https://github.com/h5p/moodle-mod_hvp/pull/588
