### ISSUE TITLE
Master is actually Dev??

### ISSUE THREAD

**Issue by richheath** [h5p/h5p-moodle-plugin#263]
More of a comment than an issue. I've just updated our test instance of Moodle with the latest code from the master branch and am getting 500 errors everywhere I turn. After investigating a little, I've discovered that your master branch is actually a kind of dev branch and you also have a stable branch. Just wanted to flag up that this might be an issue for some people who automatically assume that master is the one to install - master is what we pull from in 99% of cases.

It might be worth throwing something in the documentation about pulling from the stable branch (I couldn't find it myself, but perhaps it's already there) or creating a dev branch to work on.

I assume the error will be fixed by the time it makes it to stable, but for the record the error I'm encountering is:

`PHP Fatal error:  Class mod_hvp\\file_storage contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (H5PFileStorage::saveFileFromZip) in /srv/www/vhosts/moodle.port.ac.uk/moodle/mod/hvp/classes/file_storage.php on line 40,`

Thanks for all your hard work on this plugin!

**Comment by thomasmars** [comment]
You're correct, 'master' is a dev branch. The default checkout branch for the plugin is 'stable' and as one of the first headers in our readme.md under "usage" it says:

> If you intend to use the repository directly in production, make sure that you're using the "Stable" branch, as this is the production branch. There are no guarantees for the state of the other branches at any given time. Also make sure that all submodules are pulled as well using:
> 
> `git submodule update --init`

**Comment by richheath** [comment]
Ha ha, that'll teach me to RTFM [properly]!

Thanks again

**Comment by thomasmars** [comment]
Np, and I'll agree it is a bit strange for the 'master' branch to be a development branch, but that's unfortunately the convention we are stuck with for all our repos, so at least we are consistent in this :stuck_out_tongue:
