### ISSUE TITLE
The H5P activity description is not displayed if it contains only add an image

### ISSUE THREAD

**Issue by brian-winstead** [h5p/h5p-moodle-plugin#266]
*DESCRIPTION*
The H5P activity description is not displayed if you only add an image, you must always add text for the description to be displayed.

*STEPS TO REPLICATE*
1. Create a new H5P activity.
2. Add in the description only one image.
3. Save changes.
4. View the created activity.

OBSERVED BEHAVIOR:
The description is not displayed when you enter the activity.

EXPECTED BEHAVIOR:
The description of the activity should be shown, since an image was added as content

*REPLICATION LOCATIONS*
Moodle 3.6.3 with H5P 1.17.2.

*ADDITIONAL INVESTIGATION NOTES*
> Adding a space after the image is enough to make the description display.
> Issue occurs regardless of text editor (Atto or TinyMCE).
> Issue occurs all core themes: Boost, Clean, and More

**Comment by thomasmars** [comment]
Thanks for reporting this. I have fixed it in https://github.com/h5p/h5p-moodle-plugin/commit/00fbedc87f396a1d984ed1e26f5afb2683bb38e3 and it will be part of the next release. Feel free to test it out and give feedback on how it works for you.
