### ISSUE TITLE
Totara 12 unit tests fail with HVP

### ISSUE THREAD

**Issue by danmarsden** [h5p/h5p-moodle-plugin#268]
Totara 12 now requires a new tests/generator/lib.php file and sites using continuous integration will have unit test failures when installing the HVP plugin in their site.
It shows errors like this:

1) core_course\totara_catalog\course\core_course_totara_catalog_course_activity_type_filters_testcase::test_activity_type_panel_filter
coding_exception: Coding error detected, it must be fixed by a programmer: Component mod_hvp does not support generators yet. Missing tests/generator/lib.php.

/var/www/html/lib/testing/generator/data_generator.php:121
/var/www/html/lib/testing/generator/data_generator.php:518
/var/www/html/course/tests/totara_catalog_course_activity_type_filters_test.php:81
/var/www/html/course/tests/totara_catalog_course_activity_type_filters_test.php:131
/var/www/html/lib/phpunit/classes/base_testcase.php:600
/var/www/html/lib/phpunit/classes/advanced_testcase.php:68

@andreyamin (Totara) - is there are reason Totara has to do generate unit test failures like this  with all 3rd party plugins?

**Comment by danmarsden** [comment]
FYI - I've also reported this issue to Totara - I don't think they should be forcing all Moodle plugin developers to implement a Totara specific generator class.

**Comment by danmarsden** [comment]
I've dropped in a partially complete generator class here to show you what this looks like:
https://github.com/danmarsden/h5p-moodle-plugin/commit/785ddac8a9ae5e812fbdd5c95a1e7ea0182b82bc

That generator isn't quite right though - it's currently throwing the error:

Undefined index: machineName
/var/www/html/mod/hvp/classes/framework.php:958

**Comment by andreyamin** [comment]
Our development team is on it @danmarsden, thanks for reporting. I'll keep you posted.

**Comment by danmarsden** [comment]
Totara has confirmed they are going to fix this on their end - so H5P (and other plugins) won't need to implement this class. - closing this as there's nothing for h5p to do here.

**Comment by andreyamin** [comment]
I can confirm this will be sorted in Totara core so I believe this can be closed.
