### ISSUE TITLE
H5P Save and display option (2019031301;1.17.2)

### ISSUE THREAD

**Issue by gemguardian** [h5p/h5p-moodle-plugin#269]
Clicking on **save and display** makes me return to the course overview page instead of the module page in Moodle as you should expect.

I am using Moodle 3.5.x; H5P build 1.17.2 / 2019031301

![2019-04-28_14-06-01](https://user-images.githubusercontent.com/16559999/56864115-e9e03b00-69be-11e9-89c2-686c774f8b94.png)

**Comment by icc** [comment]
I believe this is already fixed in h5p/h5p-editor-php-library@87d5cfd but has not been released, yet.

**Comment by gemguardian** [comment]
Thank you, it seems that will indeed fix it. I will await the release to see if it does.

**Comment by otacke** [comment]
@gemguardian The update to version 1.18 of the moodle plugin solves the issue and was released today.

**Comment by gemguardian** [comment]
Thank you, I have tested it and can confirm it is been resolved.
