### ISSUE TITLE
Implement backup/restore

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#27]
... and that H5P content is successfully restored.

Must be checked after #19.

**Comment by mudrd8mz** [comment]
I just spotted missing support for Moodle backup & restore while checking the plugin for Moodle Plugins directory approval. Please note this is normally considered as a must for Moodle activity modules as users simply expect it works.

**Comment by juho-jaakkola** [comment]
See #41

**Comment by icc** [comment]
Thank you, I will add a note about this in the plugins description until we get it in place.

**Comment by vaughany** [comment]
:+1:

**Comment by vaughany** [comment]
Please note that @cgreenwood and I have implemented a solution and submitted a PR: #131.

**Comment by icc** [comment]
Great! I'll have a look and do some testing.

**Comment by falcon-git** [comment]
This was added to the last release of the H5P plugin for Moodle
