### ISSUE TITLE
Fixing compatibility issue with Totara 13

### ISSUE THREAD

**Issue by andreyamin** [h5p/h5p-moodle-plugin#271]
Totara 13 introduced some security hardening that affected H5P and a simple line of code is required.

**Comment by andreyamin** [comment]
Pull request available here to fix the issue: https://github.com/h5p/h5p-moodle-plugin/pull/272#partial-pull-merging

**Comment by thomasmars** [comment]
Please provide some more info on this.
Why did Totara make this change, what are they accomplishing, and why are they not handling the issue themselves? Is this a result of lacking metadata for the requests ?
It does not make much sense for us to add an option that is not supported for Moodle, which the plugin is for, ref: https://github.com/moodle/moodle/blob/master/lib/filelib.php#L2587.
If there is some metadata we can add on the other hand, that would tell the server that the file should not be converted to application/x-forcedownload, then that makes more sense to look into.

**Comment by andreyamin** [comment]
Hi Thomas, the pull request is now pointing to master: https://github.com/h5p/h5p-moodle-plugin/pull/291.

**Comment by andreyamin** [comment]
The upcoming Totara release contains a number of changes to the way in which cleaning and sanitisation occur throughout the product.
Information on changes made has been documented at https://help.totaralearning.com/display/DEV/Totara+13+changes+to+content+sanitisation
The change affecting the H5P module when used within Totara 13 is that we changed the default file content disposition from inline to attachment, with only whitelisted mimetypes being served inline. The change was made in order to move towards a safer, more secure default.
Plugins relying upon inline content disposition for files that are not whitelisted (basic image/media types) are now required to inform the file API that they accept the risk and genuinely want to serve inline. The means of doing this is by setting the 'allowxss' option to true.
Our implementation of these changes introduced a brand new option rather than reusing or adjusting the existing $forcedownload argument.
There were a couple of reasons to do this, but the most prominent is that the value of the force download argument originates from the client and cannot be trusted; it provides no guarantee of safety.
The force download argument is still paid attention to, but only for the whitelisted mimetypes.
For other mimetypes it is disregarded.
It was on our end a very purposeful decision in to put in place a secure default.
Thomas asked whether there was metadata that could be provided.
Essentially the allowxss option is that metadata.
What it is telling us is that the plugin is dependent upon an inline content disposition and that even if the file it wants to serve is not on our whitelist then we should serve the file with an inline disposition.
In terms of this being a Moodle plugin, absolutely we understand. 
We share a lot in common with Moodle, and we invest a lot in trying to keep the plugin API between the two products compatible.
This plugin works well within our current Totara 12 release and we're just hoping that this change can be accepted so that the plugin continues to work well with our upcoming release.
Kind regards,
Andre.

**Comment by andreyamin** [comment]
Thanks a lot @thomasmars!
