### ISSUE TITLE
Editor won't load at all after adding multiple choice question

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#277]
Hello,

I have the newest H5P-addon (1.18) and libraries in Moodle 3.5 and when I try to edit some of the existing H5P- course presentations that have multiplechoice questions the editor doesn't load at all but gives an error

See attached picture and error log from chrome console

[error.txt](https://github.com/h5p/h5p-moodle-plugin/files/3361198/error.txt)

![noeditor](https://user-images.githubusercontent.com/15193418/60699392-5108f700-9efc-11e9-97f1-87f7ad2b11fc.png)

**Comment by Jarvil** [comment]
@fnoks

**Comment by Jarvil** [comment]
Hello,

The problem seems that I cannot add multiple choice question to course presentation at all, done-button doesn't do anything and even if you remove the question save -> editor brakes down

**Comment by Jarvil** [comment]
This might have something to do with media-button which is

**Comment by icc** [comment]
It looks like it may have something do to with the translation file. Does it work if you only load Multiple Choice from the H5P Hub?
