### ISSUE TITLE
Check permission handling and access control

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#28]
Check that all the capabilities that are needed exist and that the permissions seems natural and work.

#22 must be fixed before this.

**Comment by juho-jaakkola** [comment]
The Drupal plugin has the following permissions:
 - Update libraries
 - Access all H5P results
 - Access own H5P results
 - Access h5p results for own content (created by the user)
 - Create restricted H5P content types

For example the Moodle's quiz plugin has quite a lot more than that:
 - [ ] Ability to see that the quiz exists, and the basic information about it, for example the start date and time limit
 - [ ] Ability to add a new quiz to the course
 - [ ] Ability to do the quiz as a student
 - [ ] Ability for a Student to review their previous attempts. (Review by Teachers is controlled separately)
 - [ ] Edit the quiz settings, add and remove questions
 - [ ] Edit the quiz overrides.
 - [ ] Preview the quiz.
 - [ ] Manually grade and comment on student attempts at a question.
 - [ ] Regrade quizzes.
 - [ ] View the quiz reports.
 - [ ] Delete attempts using the overview report.
 - [ ] Do not have the time limit imposed. Used for accessibility legislation compliance.
 - [ ] Receive a confirmation message of own quiz submission.
 - [ ] Receive a notification message of other peoples' quiz submissions.
 - [ ] Receive a notification message when a quiz attempt becomes overdue.

@tmkettunen @anieminen Which of these do you think are most important and should be included to the first version of the H5P plugin?

**Comment by juho-jaakkola** [comment]
I replaced quiz permissions in the previous comment with SCORM permissions because it's closer to H5P content.

**Comment by tmkettunen** [comment]
I think the most important are:
scorm:addinstance (teacher)
scorm:deleteresponses (teacher)
scorm:savetrack (student)
scorm:viewreport (teacher)
scorm:viewscores (student)

**Comment by icc** [comment]
Looks good! The biggest part of this issue will probably be locating potential issues and testing/checking that access control for ajax, files, grades etc. don't expose any vulnerabilities.
