### ISSUE TITLE
Moodle Cancel still creates a H5P

### ISSUE THREAD

**Issue by digitalskill** [h5p/h5p-moodle-plugin#280]
Steps to re-create:

- Turn editing on in Moodle

- On a course page add a new H5P Activity.

- Fill out the form as per normal

- Select an H5P item (Or cancel cannot be clicked at all)

- Click Cancel

H5P is still created on the page

**Comment by thomasmars** [comment]
Not able to reproduce, please try to update to the latest version or provide more context ( h5p version, moodle version, etc.)
