### ISSUE TITLE
Use Quiz only once in moodle

### ISSUE THREAD

**Issue by BiLachner** [h5p/h5p-moodle-plugin#284]
At the moment the user can start a quiz as often as they want. Even if I turn of repetition of the single questions (I my case "single-choice")
It would be nice to define the max number of trials that it behaves like tests in moodle.
Thanks!

**Comment by thomasmars** [comment]
Thanks, this would have to be implemented in H5P Core though ( https://github.com/h5p/h5p-php-library ) so closing this issue, please re-open it in H5P Core.

**Comment by BiLachner** [comment]
Well, may be yes or no. Because moodle has special possibilities. For me it does not make sense for "not-controlled" quizzes like at the h5p.org pages, because you can reload the quiz again ...
but if you think that should be in the core, Ill ask there. Thanks!
