### ISSUE TITLE
Unable to find constructor

### ISSUE THREAD

**Issue by KerstinSc** [h5p/h5p-moodle-plugin#287]
Hi there,
since we recently updated the plugin we're having quit a few problems while adding different content types like chart, speak the words, dictation, find the hotspots... We are able to save them but they are not showing up on the frontend. 

See for example the browser console errors for adding a chart:

Unable to find constructor for: H5P.Chart 1.2
H5P.error @ h5p.js?ver=2019052100:876"

Uncaught TypeError: Cannot read property 'getCopyrights' of undefined
    at Object.H5P.getCopyrights (h5p.js?ver=2019052100:1002)
    at HTMLDivElement.<anonymous> (h5p.js?ver=2019052100:172)
    at Function.each (jquery.js?ver=2019052100:2)
    at init.each (jquery.js?ver=2019052100:2)
    at Object.H5P.init (h5p.js?ver=2019052100:93)
    at HTMLDocument.<anonymous> (h5p.js?ver=2019052100:2716)
    at c (jquery.js?ver=2019052100:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=2019052100:2)
    at Function.ready (jquery.js?ver=2019052100:2)
    at HTMLDocument.H (jquery.js?ver=2019052100:2)

Debugging says nothing more. We're having a big installation so just reinstalling the plugin will not be a solution for us. 

H5P PlugIn: 2019052100
Moodle: Moodle 3.6.2+ (Build: 20190208)

Would be great if someone could point us in the right direction! Thanks!

**Comment by thomasmars** [comment]
Hi, please go through the troubleshooting guides at https://h5p.org/documentation/troubleshooting and https://h5p.org/documentation/troubleshooting-php.
If this produces no results, please try to reinstall/re-upload H5P.Chart from https://h5p.org/chart and check if this produces any errors.

**Comment by KerstinSc** [comment]
Hi,
debugging in moodle shows nothing but in the server error logs are warning similar to the following

[Tue Jul 30 08:20:02 2019] [warn] [client XXX] PHP Warning:  readfile(/var/opt/XXX/filedir/14/08/14086fa5fb7a152fd5a68e6ea2efca6dd6353d70): failed to open stream: No such file or directory in /var/opt/webserver/XXX/moodle/lib/filelib.php on line 2083, referer: https://XXX/mod/hvp/view.php?id=180485&forceview=1

Maybe it's the moodle version and I should wait until we are going to update the moodle core again? 

Thank you!

**Comment by thomasmars** [comment]
It looks like your server is not able to find the library files for some reason.
It does not sound like you were able to reinstall the library. Please set `$CFG->mod_hvp_dev = '1';` in your config.php (if possible for you). This will allow you to overwrite libraries when you upload them. Then go to the H5P editor on your site and upload the file you get when clicking 'reuse' -> 'download as an .h5p file' at https://h5p.org/chart. This will make sure that the files are stored properly on your server, and should result in a php error if you're not able to reinstall the library, then attempt to view the H5P again. Any error messages received during this process should be able to give us an idea of what is going wrong.
