### ISSUE TITLE
Add H5P Editor library

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#29]
H5P Content must be editable inside Moodle.

**Comment by stumari** [comment]
In H5P, users can add in video quizzes to YouTube videos among others, will this be possible in H5P Moodle module too, when it is released?

**Comment by icc** [comment]
Yes, all the Content Types will behave exactly like they do on other sites :-)

**Comment by falcon-git** [comment]
I'm not 100 % sure if the authoring tool will be part of the first release. I hope it will. When the authoring tool is released the YouTube support will be included.
