### ISSUE TITLE
Missing defined('MOODLE_INTERNAL') || die(); 

### ISSUE THREAD

**Issue by CholitoBest** [h5p/h5p-moodle-plugin#290]
It looks like defined('MOODLE_INTERNAL') || die();  is missing in following files:

* editor/h5peditor.class.php
* editor/h5peditor-ajax.class.php
* editor/h5peditor-ajax.interface.php
* editor/h5peditor-file.class.php
* editor/h5peditor-storage.interface.php
* library/h5p.classes.php
* library/h5p-default-storage.class.php
* library/h5p-development.class.php
* library/h5p-event-base.class.php
* library/h5p-file-storage.interface.php
* library/h5p-metadata.class.php

Best regards,
Olena Tatarintseva

**Comment by icc** [comment]
Hi,
These files are part of generic libraries used for other systems like WordPress and Drupal as well, this means that adding Moodle specific code is not possible.

**Comment by OlenaTatarintseva** [comment]
OK, thank you for your response.
