### ISSUE TITLE
Urgent: Editor doesn't work at all in finnish after updating to 1.19

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/h5p-moodle-plugin#293]
Hello,

After updating mod_hvp to 1.19 editor doesn't load at all when using Finnish language, it says "Missing translations for library core" if you switch language to english editor will show. @thomasmars @icc 

![error](https://user-images.githubusercontent.com/53904029/63142503-b8818e80-bff2-11e9-8255-342b76cb0365.PNG)

**Comment by thomasmars** [comment]
Hi, thanks for reporting this.
It was a problem with the finnish translation that was contributed at https://github.com/h5p/h5p-editor-php-library/pull/83/commits/d730a250a4d82f4bec1ab3567c5f2283f8b419fa#diff-6b2cd64c0015a6a0d6483a7c6d3b28f8R156. Sorry that we were not able to catch this before the release. We're doing a full validation of the language files and then I'll release a new version as soon as possible. If you would like to do a quick patch for your site you can add `'.` at the end of line 156 in fi.js as shown in this commit https://github.com/h5p/h5p-editor-php-library/commit/7fc23cda93ae4225320f4903017c67e8f4294157#diff-6b2cd64c0015a6a0d6483a7c6d3b28f8R156.

**Comment by thomasmars** [comment]
Version 1.19.1 with the fix for translations are now out, thanks again for reporting this.

**Comment by CJROD101** [comment]
Hello,

After updating mod_hvp to 1.20,2 "Missing translations for library core" . @thomasmars @icc




![image](https://user-images.githubusercontent.com/39109866/77216427-d6aaf200-6adf-11ea-87c3-12c32edc0ab5.png)
