### ISSUE TITLE
H5P - Interactive Video Fr translation issue

### ISSUE THREAD

**Issue by lapie002** [h5p/h5p-moodle-plugin#295]
Hi,

The modal's content of the Interative Video activity has some weird translation issue : 

![modal](https://user-images.githubusercontent.com/13002308/63352996-10403280-c330-11e9-845e-85f23aa81a62.png)

Does anyone have the same issue ?
I am ussing Mooodle 3.6 with boost template, any help would be appreciated.

Bruno

**Comment by thomasmars** [comment]
Hi, I tested this with the latest H5P plugin 1.19.1 (Build: 2019081600) , and Moodle 3.7 (Build: 20190520) with the boost template, and the following H5P libraries:
- Interactive Video (1.21.0)
- Interactive Video Editor (1.21.5)
- Guided tour (1.0.3)
Please let me know your version of these libraries. I'm not able to reproduce the issue you're observing.
I suggest updating your plugin and libraries to the latest version and try again.
If it still occurs check your console for any errors or conflicting CSS.

**Comment by lapie002** [comment]
Hello Thomas,

I moved my request to Interactive video issue page (I thought it would be more relevant since it concerns only interactive video) : https://github.com/h5p/h5p-moodle-plugin/issues/295

I added more descritption of my issue that's only shows up when Fr - French is selected in the language menu. English translation is working properly if you want to compare.

Bruno
