### ISSUE TITLE
Error on mobile app

### ISSUE THREAD

**Issue by haietza** [h5p/h5p-moodle-plugin#299]
The [Mobile support page](https://docs.moodle.org/dev/Mobile_support_for_plugins#Moodle_plugins_with_mobile_support) lists this module as supported in the Moodle mobile app, however we see the "site is not configured properly for displaying mobile H5P content" error when we try to access an H5P activity through the mobile app. Is there another setting we need to configure to make this work? Thank you!

**Comment by thomasmars** [comment]
Please follow Moodle's guide for enabling mobile support for your site: https://docs.moodle.org/37/en/Moodle_app_guide_for_admins. Note that "Frame embedding" must be enabled for the site as well for H5P to work in the mobile app.

**Comment by haietza** [comment]
@thomasmars Shouldn't that setting no longer be necessary as of https://tracker.moodle.org/browse/MDL-64281?

**Comment by thomasmars** [comment]
I'm not sure what version that ticket is included in and I don't know the details of it. I tested with Moodle 3.7.1+ (Build: 20190830), and the setting is still needed there to make H5P content show up.
If it is still not working I suggest having a look in your browser console and php error log for any clues.
