### ISSUE TITLE
Inconsistency between library versions and Moodle plugin version

### ISSUE THREAD

**Issue by ebithell** [h5p/h5p-moodle-plugin#303]
We are unable to use the Course Presentation or Branching Scenario content types on our Moodle 3.5 site via the Moodle plugin, apparently because of an inconsistency in the versions required and available.

At the moment we have version 1.17 of the Moodle plugin. We could update to 1.19.1 via GitHub, but nothing is available beyond that version. However when we try to update Branching Scenario, Column or Quiz, there are errors citing "This site is currently running version 1.20, whereas the required version is 1.23 or higher. You should consider upgrading and then try again." Course Presentation doesn't show as having an update available, and we can't update to version 1.23, because it isn't available.

I've tried forcing updates by setting $CFG->mod_hvp_dev and $CFG->mod_hvp_aggregate_assets in config.php, but that doesn't help. So we can't update the content type libraries, because the required version of the plugin isn't available.

Could someone amongst the developer team take a look at this? Unfortunately because this is a version number and compatibility issue, this isn't the sort of issue where it would be possible for us to work on a contributed solution.

**Comment by thomasmars** [comment]
Updating your Moodle H5P plugin to version 1.19.1 will solve this.
Branching Scenario's dependency is to the H5P Core, not to the Moodle H5P plugin version.
Version 1.19.1 of the Moodle H5P plugin contains version 1.23 of H5P Core, so it will allow you to update the content types which require version 1.23.

**Comment by ebithell** [comment]
Thanks for the speedy explanation. As an improvement (since it's not a bug) maybe you could consider changing the wording of the error message, so that it specifies more clearly which plugin is the cause of the issue, and which needs to be updated? But as you say, upgrading the H5P plugin should fix our issue.

**Comment by thomasmars** [comment]
Yes, I agree :) thanks

**Comment by ebithell** [comment]
I've tried this, and unfortunately it's not working. I've upgraded the plugin to tag 1.19.1 from GitHub (verified both in version.php and in the Plugins Overview page) but I'm still getting the attached errors when I try to upload the Course Presentation example from h5p.org (and similar errors if I try to update any of Branching Scenario, Column and Quiz).
![h5p_course_presentation_error](https://user-images.githubusercontent.com/12151818/65968380-f891b900-e45a-11e9-8c79-c203e68d465f.png)

**Comment by thomasmars** [comment]
If you're using the module directly from Github ensure that you've updated the submodules, as explained in the "Usage" section in the readme: https://github.com/h5p/h5p-moodle-plugin#usage.
If you're still experiencing this after updating the submodules, please let me know.

**Comment by ebithell** [comment]
You're absolutely right - I was aware of that step but had forgotten to carry it through. Apologies for the confusion on my part, and everything is working now. Many thanks for the help!!
