### ISSUE TITLE
Embeded webpage url cant scroll

### ISSUE THREAD

**Issue by mjencabh** [h5p/h5p-moodle-plugin#309]
We cant scroll embeded book-pages or webpages at all...
I have to manually set size height for every single page and deactivate "Display action bar and frame" for it to work in page. Hovever everything malfunction on full screen again... read something about editing libary.json could some one please advice?? Really in need of help asap.

**Comment by thomasmars** [comment]
Hi, what is a book-page ? or embedded webpage and how does it relate to the plugin ?
Do you have a live example with the issue, or do you have some steps to reproduce this ?

**Comment by mjencabh** [comment]
Yeah sorry for the term :) its just an embedded page of an online book.
I can give you a account so you can see for your self.?

**Comment by thomasmars** [comment]
I'm not following, is your online book an H5P content type ?
Is this happening for all your embedded content or just this content type ? 
Can you post screenshot and check your browser's console for any errors ?

**Comment by mjencabh** [comment]
We are using an extern partner www.systime.dk they provides the online books for our students.
Every page is then linked in Moodle (embedded) with a link to the page/chapter that needs to be read.
It is happening to all embedded content as if there where no code accepting scroling.
https://www.dropbox.com/s/05tqgpie3dpz5w1/sk%C3%A6rmbillede%202019-10-28%2014.51.28.png?dl=0
The picture is showing some of the page but not all- if I change value of height to 1200 it would be shown on page but not in fullscreen. non of them with possibility of scrolling as mentioned.
Cant get a picture of the fullscreen but i thin it says it all in the text/picture. ?
Im using Chrome and Firefox, both not working.

**Comment by thomasmars** [comment]
This is not an H5P, as far as I can see ?
I think you're posting in the wrong forum.
If you have some developer resources they can inspect the page to see why you're not getting any scrollbars, could be conflicting css or a script. 
But as far as I can see this is not related to any H5P content type or the H5P plugin for Moodle.

**Comment by mjencabh** [comment]
Ok thx- i have reposted this at moodle- so hope they can figure it out.
