### ISSUE TITLE
JPG-file extension isn't allow anymore in mod_hvp 1.20

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/h5p-moodle-plugin#312]
Hello,

We have noticed that JPG-file extension isn't allowed anymore in mod_hvp 1.20 only lowercase .jpg works, in mod_hvp 1.18 JPG works.

Please fix this bug. This concerns also h5p.org.

**Comment by thomasmars** [comment]
Hi,
Thanks for reporting this. I've made a fix in https://github.com/h5p/h5p-editor-php-library/commit/bd871a3181f3e4a343351ae6a22d773a74d928b7

**Comment by Urpokarhu1** [comment]
Hello,

When is this going to be available?

**Comment by thomasmars** [comment]
I've just released this as part of version 1.20.1

**Comment by Urpokarhu1** [comment]
Great,

Thanks.
