### ISSUE TITLE
Hardcoded to english?

### ISSUE THREAD

**Issue by dinism** [h5p/h5p-moodle-plugin#315]
"H5P fetches content types directly from the H5P Hub. In order to do this the H5P plugin will communicate with the Hub once a day to fetch information about new and updated content types. It will send in anonymous data to the Hub about H5P usage. Read more at the plugin communication page at H5P.org."

This text appears in the message after install hvp. I founded it in line 274 of upgrade.php

**Comment by thomasmars** [comment]
Hi, I believe there is no point in translating any installation strings as the plugin will not have any translations available at installation. Translations must be fetched after the plugin is installed.
