### ISSUE TITLE
H5P editor doesn't work at all with IE11

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/h5p-moodle-plugin#319]
Hello,

H5P editor doesn't load at all with Internet Explorer 11 & mod_hvp 1.20.1 &  Moodle 3.5 it just says "waiting for javascript" and no editor is loaded. There is no error in the console.

 @icc @thomasmars 

![java](https://user-images.githubusercontent.com/53904029/70237249-6e721380-176f-11ea-8d4d-811c5807bc7c.PNG)

**Comment by thomasmars** [comment]
Thanks for reporting this, I've made a fix for it at https://github.com/h5p/h5p-moodle-plugin/commit/d4c6aa0303ad06ecab9bf859233a6eb6e856b1e0, which you can apply locally if you wish. It will be included in the next official release.
