### ISSUE TITLE
H5P activity completion does not go into course calendar

### ISSUE THREAD

**Issue by cvaughnBB** [h5p/h5p-moodle-plugin#321]
The H5P activities do not display on the course calendar when there is a expected completion date set. 

Steps to recreate:
View course, go to Getting Started section, scroll down to h5p Getting Started activity, click edit pencil icon, scroll down to activity completion, expand options and note that the expect completed on date has been enabled
- go to course calendar and look at date, and note that only the discussion forum (not the h5p activity) appears there in the calendar.

**Comment by thomasmars** [comment]
There's a pending ticket for this at https://h5ptechnology.atlassian.net/browse/HFP-1550
