### ISSUE TITLE
H5p video not displaying (moodle plugin 1.20.1, interactive video 1.21.6)

### ISSUE THREAD

**Issue by dirkcgrunwald** [h5p/h5p-moodle-plugin#324]
We recently upgraded our Moodle instance and installed V1.20.1 of the moodle h5p plugin. We have two sites using the same software and configuration (it's all docker behind the scenes, so exactly the same). The H5P libraries were upgrade and video player 1.20.6 installed and all videos upgraded to that version. One site has ~450 videos, the other has ~3000.

On the first site, everything is working fine. On the second (with more videos), the videos don't show and the display when you "Edit Settings" an existing video looks like the following:
![image](https://user-images.githubusercontent.com/989516/71773035-2f241780-2f13-11ea-9caa-4c2d5f1bae00.png)

I get the same screen when I go to add a new H5P interactive video, so it would appear to be an issue with the library. Other content types (e.g. quiz) appear to work. We make little to no use of the other types and my first thought is that something changed when upgrading the videos.

Any idea how to fix this?

**Comment by thomasmars** [comment]
Looks like you're missing the Interactive Video library. Try to upload Interactive Video through the editor or through the library administration page, and check your error logs to see if it fails.
You can check what libraries you have installed on the [library administration page](https://h5p.org/library-administration), looks for the Interactive Video and Interactive Video Editor libraries.

**Comment by dirkcgrunwald** [comment]
Yes, we though the issue we're having is likely related to having some file corrupted or incompletely uploaded because the symptoms are similar to https://h5p.org/node/20592 and  https://h5p.org/node/20592

However, after navigating through the Moodle filesystem interface, all the file contents for the Interactive Video and Interactive Video Editors are there, and changing both the sha1 hashes and contents show them to be the same.

I also tried uploading new interactive video files (using the demo from h5p.com) and that had no effect either. From looking at the code, it doesn't appear that the libraries are always updated when a new *.h5p is uploaded, but I may have missed that part.

Is there a way to force the library files to be refreshed and/or checked against fresh files from the hub and/or uploaded h5p files? I'm working through the source to see if that's possible.

In the mean time, we're doing a fresh install of our moodle site since there's obviously some database issue.

Alternatively, is there a way to determine which file is possibly corrupted or missing? I'm working through the moodle 'files'

**Comment by dirkcgrunwald** [comment]
We eventually gave up and started from a clean moodle install because we could never narrow down what file(s) were corrupted and causing the failed javascript issues. There were no log issues we could find, but later, when doing course backup (using moosh) we saw several messages on missing files and the backups were corrupted or produced non-working restores.

A useful remedy would be a mechanism to remove and reinstall the library files.

**Comment by dariothornhill** [comment]
I'm having a similar issue with the Content Presentation Editor. The script files are present on the file-system and I can request them using pluginfile.php. In the browser network there are no failed requests. The console reports H5P.DragNBar.FormManager is undefined. If I pause execution before the first use of DragNBar and manually copy the code from the DragNBar  scripts into the console the editor will appear.  It seems as though the editor doesn't request all of the dependencies.

I can't ask my content editor to go through that procedure as he would be lost. Can anyone help with a permanent fix?

**Comment by thomasmars** [comment]
please check your browser console for any errors and your php error log for any errors.

**Comment by dariothornhill** [comment]
The errors I reported above about the undefined object are from the Browser console. There were no error messages in the php log.

The issue was fixed by busting all of the caches from the server up to the browser cache. I suspect corrupted files were cached from an incident with the moodledata that occurred before so the reinstall and cache busting helped.

Thanks for the response!
