### ISSUE TITLE
H5P Full Screen Button not showing on Mobile App

### ISSUE THREAD

**Issue by SanatSharma** [h5p/h5p-moodle-plugin#325]
Hi,
The H5P player is not showing the fullscreen button on my mobile app, across both IOS and Android. 
Upon looking at the code on mobile, the H5P.fullscreenSupported variable comes out as false, leading to the fullscreen button not showing. Furthermore, the H5PIntegration.fullscreenDisabled is set to true on player load.
I tried testing fullscreen functionality manually by using document.documentElement.webkitRequestFullScreen() which worked temporarily. 
The video is an interactive activity.

**Comment by SanatSharma** [comment]
Attaching a screenshot of the player. Using the November 2019 release of the plugin. The player works well on the browser, but not on the app.
![image](https://user-images.githubusercontent.com/14241701/71807911-6bca4d00-3092-11ea-8103-a8cc1d98fa2f.png)

**Comment by icanpj** [comment]
Did you find a solution to this yet?

I can see that you are using h5p on Moodle Mobile. This is a need by many many users who seek to use h5p interactive video on moodle Mobile but are unable to, since the full screen is not proper. The semi or oversized screen is a poor experience. I am also hoping that somebody frm the Moodle Mobile domain should be able to look into it and give some solution or help.

**Comment by icc** [comment]
H5P relies on the browser, iframe or webview to offer the fullscreen capability/API. If it's disabled the button will disappear from the content. I'm not sure why this wouldn't be enabled in the app, but there is probably a reason.

**Comment by SanatSharma** [comment]
I'm not sure about that. The default player with Moodle, videojs does allow and work in fullscreen mode in the app. Can you provide any guidance on how to debug the problem?

**Comment by icc** [comment]
I would think you would have to set up the app development environment to be able to debug this. Though, I won't say there may be some option or something we've overlooked when setting the mobile view for the modules: [classes/output/mobile.php](https://github.com/h5p/h5p-moodle-plugin/blob/eb9c450ed8823a4b200a9c9810ca5ff47f6ce5f9/classes/output/mobile.php)

**Comment by SanatSharma** [comment]
@icc I found out why full screen button doesn't show. In embed.php on line 39, when authentication request is received from mobile, $disablefullscreen is set to false. I removed that line and now the fullscreen button does show up but behaves erratically sometimes. I was having some issues with it in a Moodle 3.7 installation but it seems to work fine on Moodle Desktop on a fresh Moodle 3.8 installation. In addition, it seems to work on a phone simulation but doesn't actually go to full screen on my actual hardware andriod device. Would it be possible to investigate a bit on your end?
Why was that check put in, in the first place?

**Comment by icc** [comment]
You are right, I think that was the problem, it looks like it will work and the button is displayed but it doesn't work. However, I will double-check this.

**Comment by SanatSharma** [comment]
Fix
Locate the following file + line: js/h5p.js#L35 on your system.
Next, replace it with the following line:

  H5P.safariBrowser = navigator.userAgent.match(/Mac OS X.+Version\/([.\d]+)/);

This should make sure fullscreen is only disabled for older Apple devices.
