### ISSUE TITLE
Unable to load interactive video module on Moodle 3.8.3

### ISSUE THREAD

**Issue by mikewilday** [h5p/h5p-moodle-plugin#331]
I am having issues getting the content for the interactive video H5P plugin to load. I was able to successfully install the plugin but it just spins and spins and never loads the content. What should I do to troubleshoot this issue? I tried uninstalling and reinstalling the plugin and I am getting the same issue.

**Comment by thomasmars** [comment]
Hi, please see https://h5p.org/documentation/troubleshooting and https://h5p.org/documentation/troubleshooting-php for troubleshooting your issue and providing additional php related information

**Comment by mikewilday** [comment]
I just discovered that Adblock Plus extension was causing conflicts and preventing the content to load in the frame. Turning off the extension in Chrome immediately allowed the content to load. You might want to mention that as a possible issue to your users.
