### ISSUE TITLE
h5p hub Plugin load error

### ISSUE THREAD

**Issue by nczirjak-acdh** [h5p/h5p-moodle-plugin#343]
Hi,

i am using the h5p hub and it iw working weel except some type has problem to load.

For example:
- course presentation
- aggamotto content types

these plugins are not loading and i have a JS error:

Error while loading script 
error { target: script, isTrusted: true, srcElement: script, currentTarget: script
, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
h5peditor.js:124:23
    libraryRequested https://domain/mod/hvp/editor/scripts/h5peditor.js?ver=2019111300:124
    onerror https://domain/mod/hvp/editor/scripts/h5peditor.js?ver=2019111300:81

it seems like that the h5p hub cant find these plugins files.

I updated h5p and checked every browser. Also checked in Firefox and chrome, the same error and my moodle version is 3.7.2

thanks!

**Comment by thomasmars** [comment]
Please enable php developer debugging and check your php error log (https://docs.moodle.org/38/en/Debugging)

**Comment by nczirjak-acdh** [comment]
[Mon May 18 09:28:25.356088 2020] [php7:notice] [pid 3791] [client 172.17.0.1:39228] Default exception handler: Sorry, the requested file could not be found Debug: \nError code: filenotfound\n* line 494 of /lib/setuplib.php: moodle_exception thrown\n* line 2074 of /lib/filelib.php: call to print_error()\n* line 4953 of /lib/filelib.php: call to send_file_not_found()\n* line 44 of /pluginfile.php: call to file_pluginfile()\n, referer: https://domain/course/modedit.php?add=hvp&type=&course=59&section=1&return=0&sr=1

**Comment by thomasmars** [comment]
So it appears you don't have the file or for some reason it can't be found. Try uploading the content types that this fails on as an Admin who can update libraries from an example content on H5P.org to your site, ensure that the files for the content types get replaced and check if you encounter any errors.

**Comment by nczirjak-acdh** [comment]
thanks! if i am upload the example then it is working :)
