### ISSUE TITLE
Fatal error directly after installing the plugin!!

### ISSUE THREAD

**Issue by naamaan** [h5p/h5p-moodle-plugin#348]
Hi,
I'm using Moodle 3.8, I've just installed the H5P module and got the attached fatal error!
![Annotation 2020-06-22 201528](https://user-images.githubusercontent.com/2176593/85316917-3c838d00-b4c6-11ea-965d-c10a35ba4d53.png)

**Comment by icc** [comment]
Sounds like you've installed it by checking out the git repo?
Did you remember to run `git submodule update --init` as per the README.md file?

**Comment by naamaan** [comment]
Yes, I did checkout the git repo into the `stable `branch, but I'm not using the `git submodule` so I thought I don't need to `update --init`.
Any way, I downloaded the zip file from Moodle plugins (https://moodle.org/plugins/download.php/21001/mod_hvp_moodle39_2020020500.zip) and got the following error directly when turning editing on in a course:

![error](https://user-images.githubusercontent.com/2176593/85368426-e9482380-b533-11ea-9809-9912497c8cd7.png)

What's the wrong in my installation!?

**Comment by naamaan** [comment]
Duplicate of #101

**Comment by icc** [comment]
I'm wondering if there may be an issue with file permissions or similar? I tried extracting the plugin zip file in a fresh install of Moodle and it just works.

**Comment by naamaan** [comment]
The `hvp/` directory and everything in it is owned `www-data` with` rwx `on it's content :(
![2020-06-23 10_23_22-](https://user-images.githubusercontent.com/2176593/85373282-b6a22900-b53b-11ea-8551-b9c4e5ee7348.png)

**Comment by naamaan** [comment]
I gave 777 recursively for the whole moodle directory, and it worked now.
Thanks lot.
