### ISSUE TITLE
error/invalidhvp

### ISSUE THREAD

**Issue by Vlad-mo** [h5p/h5p-moodle-plugin#358]
Im unable to open the h5p activity my moodle 3.9.1 instance.
****
Php version: php7.2
MySQL: 5.7.30
mod(hvp): 1.20.2 (2020020500) 

**The debug infromation are like this:**

error/invalidhvp
More information about this error

×Debug info:
Error code: invalidhvp
$a contents:

×Stack trace:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 331 of /mod/hvp/classes/view_assets.php: call to print_error()
line 46 of /mod/hvp/view.php: call to mod_hvp\view_assets->validatecontent()

The Output from the browser console look like this:    
Uncaught ReferenceError: H5PIntegration is not defined
    t https://h5p.testmoodle.com/mod/hvp/library/js/h5p.js?ver=2020020500:997
    <anonymous> https://h5p.testmoodle.co/mod/hvp/library/js/h5p.js?ver=2020020500:2717
    jQuery 4
        c
        fireWith
        ready
        H

I did also update de h5p activities but it did not help.

If you guys have an solution for this, kindly let me know ,

**Comment by thomasmars** [comment]
The content could not be found in your database or your database is not accessible. Ensure that the database is setup properly and that H5Ps get stored there properly when you're creating or uploading them.
