### ISSUE TITLE
Upgrading to 2020080400 creates a field with wrong default value

### ISSUE THREAD

**Issue by ewallah** [h5p/h5p-moodle-plugin#359]
install.xml:
`<FIELD NAME="completionpass" TYPE="int" LENGTH="1" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>`
upgrade.php
`new xmldb_field('completionpass', XMLDB_TYPE_INTEGER, '1', null, null, null, 0, 'timemodified')`

=> php admin/cli/check_database_schema.php
```
-------------------------------------------------------------------------------
hvp
 * column 'completionpass' should be NOT NULL (I)
-------------------------------------------------------------------------------
```

**Comment by thomasmars** [comment]
yes. you're right. I don't see this breaking anything, but it should be fixed. We would love a pull request for with a fix.

**Comment by Peterburnett** [comment]
It can break some CI systems. Caused me some issues this morning. I can fix this. PR incoming
