### ISSUE TITLE
H5P activity shouldn't be added to gradebook if it doesn't have any questions

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#36]
Currently an entry will be added to the gradebook even if the H5P activity doesn't have any interactive content (questions that the user answers).

Is there a way for the H5P content to tell Moodle whether it contains questions that are usable for grading?

**Comment by icc** [comment]
Unfortunately, there's no way of telling if the interactive content gets a score until results are submitted. We are working on a solution for determining this when the content is saved and using the server side to evaluate the answers. But until that is in place we'll either have to store a default max-grade when creating the content or store when the first results are in. I see advantages and disadvantages with both solutions, so the question is what fits those who're going to be using it best?

H5P Content is mostly tasks so storing the max score before any of the results are in will make it possible to see which tasks hasn't been completed yet.

**Comment by falcon-git** [comment]
In practice until a better solution is in place a hard coded list of content types that can't have scores could be added to the plugin or similar. Not in this repository, but as a patch. I'm also thinking of adding xAPI profile in library.json in a future version. That could be used to determine if the content type will report any results and this might arrive sooner than the backend evaluation.

(Side note:
xAPI profile is intended for use cases like this one, but also generally to let systems know what kind of statements to expect from a content type.

For instance if a content type uses the profile H5P-Question-1.0 it knows that the question is done when you get an answered statement with results.completion = true, if the profile is H5P-Content-1.0 it knows that the content is done when you get an experienced statement. The details in the examples mentioned here is not important and probably will be different if we decide to go for this, but the concept is important I think.)

**Comment by lewiscarr** [comment]
You can hide any activity from the gradebook in Moodle (Turn editing on within the gradebook and edit the item and hide), but still have the activity itself available within the course.

**Comment by thomasmars** [comment]
This needs to be implemented in core, closing this issue until core supports evaluating if a content has a score.
