### ISSUE TITLE
Error with Oracle

### ISSUE THREAD

**Issue by s-cenni** [h5p/h5p-moodle-plugin#38]
Hi,
I installed the plugin with Moodle 2.8 and Oracle. When I imported my first content I got an error due the use of keyword LIMIT in "classes/framework.php" line 302. Oracle (and some other DBMS) doesn't support LIMIT 
Maybe using $DB->get_records_sql($sql, array $params=null, $limitfrom=0, $limitnum=0) could work..

Removing the LIMIT condition the query works.
Thank you for the plugin!!!!

**Comment by icc** [comment]
Hi! Thank you for reporting. We haven't done much testing with other databases yet, but we should be compatible with all the databases which Moodle supports. Hopefully, we get this fixed and some more testing done before the final release.

Feel free to contribute a Patch or Pull Request if you want to :-)

**Comment by s-cenni** [comment]
hi! I tried to create a pull request with my patch. I hope it works well!
Bye
Sara

**Comment by icc** [comment]
Good work :-)
