### ISSUE TITLE
Something wrong with the git submodule?

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#39]
There's something funny going on with the git submodule:

```shell
$ git status

	modified:   library (new commits, modified content)
```

```
$ git submodule update 

    fatal: reference is not a tree: e3aa6323f55acd635b8b0056f7ab92b76043f9d9
    Unable to checkout 'e3aa6323f55acd635b8b0056f7ab92b76043f9d9' in submodule
    path 'library'
```

**Comment by juho-jaakkola** [comment]
My bad. I was checking out `HEAD` instead of the `2.0.2`tag.

With the instructions in the README everything works fine:
```
git clone --branch 0.2.0 https://github.com/h5p/h5p-moodle-plugin.git hvp && cd hvp && git submodule update --init
```

**Comment by juho-jaakkola** [comment]
I'm not familiar with git submodules. If someone knows what exactly causes the trouble with the current `HEAD`, I'd be interested to know.

**Comment by icc** [comment]
That is strange. Usually, that means that the commit h5p-moodle-plugin want doesn't exist. This can happen if someone forgot to push the submodule. But I guess it can also happen if there's some trouble fetching the submodule's changes. Not sure what happened in this case, but good that you got it working!
