### ISSUE TITLE
Can't run cron task anymore

### ISSUE THREAD

**Issue by dylem** [h5p/h5p-moodle-plugin#44]
Hi, Since I added the plugin I can't run the cli/cron.php task anymore, is it a known issue and is there a solution please ? Thanks for the awesome work !

![](https://puu.sh/o6OkU/7fa3eb9862.png)

**Comment by icc** [comment]
I have seen some others run into the issue as well, but I haven't been able to pinpoint the culprit. Have you just recently installed the plugin? You could try to clear the caches in Moodle and see if that helps.
What version of PHP are you running?

Thank you for reporting the issue.

**Comment by fnoks** [comment]
Maye the code need to require the file where the function is defined? Like it is done here:
http://xref-diff.mukudu-dev.net/moodle26/mod/scorm/datamodels/scormlib.php.source.html#l524

**Comment by dylem** [comment]
@icc Yes I recently insalled the plugin, and clearing the caches in Moodle doesn't help :/
Version of PHP : PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33)

@fnoks Then I guess the issue can't be resolved that easily :/

**Comment by icc** [comment]
@dylem Do you know if you have any opcode caches running? Like [OPcache](http://php.net/manual/en/book.opcache.php) or [APC](http://php.net/manual/en/book.apc.php)?
Are you using a web-hosting service or is this your server?

My guess is that it has something to do with the PHP version or settings. I will note down the issue and do some testing/debugging of my own when I have a some spare time.
We have to get this fixed before the next release of the plugin.

**Comment by dylem** [comment]
@icc I am using CloudWays as host. I don't know if I have any opcode caches running sorry. Thanks  a lot for your help :+1:

**Comment by dylem** [comment]
Sorry, did you find a way to fix it ? I need to run those tasks for statistics now :/

**Comment by matbury** [comment]
Also running into the same problem on a localhost LAMP stack provided by Bitnami. The LAMP stack, Moodle, and the H5P plugin are fresh installs.

**Comment by icc** [comment]
You can try adding a backslash`\` in front of the function on _line 101_ of `mod/hvp/classes/framework.php`, it should look like this:
`$data = \download_file_content($url);`

Let me know if that works for you.
If not you can disable the scheduled H5P task until we manage to create a proper fix. You should be able to do this through Site admin -> Server -> Scheduled tasks, or:
`/admin/tool/task/scheduledtasks.php?action=edit&task=mod_hvp%5Ctask%5Clook_for_updates`

This way, at least, your other cron tasks will run.

**Comment by falcon-git** [comment]
Did any of icc's suggestions work for those struggling with this? We're aiming for an official release in May/June and really want to get to the bottom of this.

**Comment by nadavkav** [comment]
I had the same issue.
Solved it by adding the following line:
require_once($CFG->libdir . '/filelib.php');
to the beginning of the file
mod/hvp/classes/framework.php

**Comment by nadavkav** [comment]
I am in the process of making some pull request for several issues, should I have one for this bug too? (or you already fixed it && someone can confirm it solved their issue too)

**Comment by icc** [comment]
Feel free to make a pull request :-)

It would be nice if you could add the issue referance`h5p/h5p-moodle-plugin#44` to the commit as well so everyone can see that something has been done about this issue.

**Comment by icc** [comment]
Merged in the suggested solution and got no errors when running cron.

Please re-open if you're still having issues.
