### ISSUE TITLE
Add Intro element above video player

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-moodle-plugin#46]
It's very common to Moodle modules to have an Intro form element that is displayed to the users at the top of the module's main page. In H5P's case, above the video. and it usually includes some instructions for students about the specific activity or resource.
(I am not sure, but it could be actually required to be implemented by Moodle HQ if it is going to be approved by them, and added to moodle.org/plugins database)

Please see if you can add one to the hvp module.

**Comment by icc** [comment]
This is a good suggestion, we will look into it.

**Comment by nadavkav** [comment]
Ok. I have already implemented it (as we already needed it)
I will send a PR

**Comment by icc** [comment]
Very good, do that and we will get it in as soon as possible. Thank you!

**Comment by icc** [comment]
How is it looking, will there be a PR?

**Comment by nadavkav** [comment]
Sorry, got very busy with Moodle 3.1 QA & Bugs (as it about to be release any day now)
Give me a few minutes... ( as I have the PR ready )

**Comment by nadavkav** [comment]
Please review the PR.

btw, I am already thinking on a next version, with a new settings that allow me to chose if the Intro is above or after the H5P object. I think it would be useful. we'll see...

**Comment by icc** [comment]
Works well, did some adjustments to support earlier version for Moodle as well. Thank you, good work!

**Comment by nadavkav** [comment]
Great. thanks!
