### ISSUE TITLE
H5PFrameworkInterface: comment both methods getnumAuthors & getLibraryStats

### ISSUE THREAD

**Issue by lesandie** [h5p/h5p-moodle-plugin#53]
I got this error when uploading h5p content to moodle:

`Fatal error: Class mod_hvp\framework contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (H5PFrameworkInterface::getLibraryStats, H5PFrameworkInterface::getNumAuthors) in /var/www/moodle/mod/hvp/classes/framework.php on line 983`

So in order to avoid declaring the framework class abstract i've commented both H5PFrameworkInterface methods until they are implemented in the framework class

Now it works.

Just for you to know .... 

BTW nice work on the plugin!

**Comment by icc** [comment]
This issue should be sorted out now. 

To avoid issues such as this I recommend sticking to the tagged versions in the future, unless you're a developer of course.
