### ISSUE TITLE
Feature request: Option to display Youtube video thumbnails while hovering timeline progress bar

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-moodle-plugin#58]
It would be nice if we could control the visibility of YouTube video thumbnails while hovering the timeline progress bar, as it is abailable on YouTube.com original video player.

Maybe, it has to do with YouTube Video Player API param: showinfo?
https://developers.google.com/youtube/player_parameters#showinfo

**Comment by falcon-git** [comment]
Not exactly sure what you mean here. You want the thumbnails to appear in Interactive Video and/or all videos in H5P when hovering over the seek bar?

**Comment by nadavkav** [comment]
Be able to hover over the video time line progress bar with the mouse pointer and see a thumbnail of that second (It's a youtube feature, we should probably pass to the player when it initiates)

![image](https://cloud.githubusercontent.com/assets/231168/15015497/ec7e7548-1214-11e6-8197-59da0ab5241f.png)

**Comment by nadavkav** [comment]
We have made some research, and it seems Google/YouTube does not allow (expose) this feature in the YouTube SDK. maybe someday...

Closing :-(

**Comment by NehaKushwah993** [comment]
Hi, Is this provided by youtube now?

**Comment by otacke** [comment]
[YouTube's iframe player API](https://developers.google.com/youtube/iframe_api_reference?hl=en) doesn't mention anything about this feature.

**Comment by NehaKushwah993** [comment]
ok thanks
