### ISSUE TITLE
grade integration?

### ISSUE THREAD

**Issue by adamtong1110** [h5p/h5p-moodle-plugin#6]
The h5p results will be stored in the moodle grades? As i am using H5P in drupal currently, the h5p results only record the result in last attempt, but Moodle support multiple attempts, so will all the results recorded?

Thanks!

**Comment by icc** [comment]
Yes, we will use the grade system in Moodle to store the results. I'm not 100 % sure that there will be multiple grades for each H5P completed event, but it seems reasonable. However, it might be that we have to be consistent with the other H5P platforms. Also, there's the question of how multiple events from the same user session should be handeled. It might be that people want to configure how it behaves.

I will give an update when I know more.

**Comment by icc** [comment]
Implemented in the Beta version available at https://h5p.org/moodle
