### ISSUE TITLE
Use Moodle's Repository API to get a video URL into Interactive Video content type

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-moodle-plugin#85]
Moodle provide a Repository API that enable any plugin to enjoy a pluggable framework of repositories that can prove easy search and retrieval of video URLs from various sources (web and local repositories). It is the standard way for content creators (and students) to input video URLs.
It could be very useful to integrate it with the "Upload/embed video(s)" Tab in the Interactive video content editor.
![image](https://cloud.githubusercontent.com/assets/231168/16279849/824c7904-38c5-11e6-8fcf-f5e7ad301507.png)

You can see it in action when you add a URL resource to a course.
https://github.com/moodle/moodle/blob/master/lib/form/url.php#L122
https://github.com/moodle/moodle/blob/master/lib/form/url.js

**Comment by falcon-git** [comment]
Thank you for sharing. I hope we can do something here. If and when we do it we have to find a clean way of doing this especially for Moodle but also make room for similar integrations for the other platforms we support. Maybe the Drupal Media module or something can be plugged in using the same mechanisms that we might develop for Moodle?

**Comment by nadavkav** [comment]
I am not sure if it is a good idea to mix Drupal and Moodle.
I will dig into the Interactive Video Editor "Upload video" function 
and suggest how we should integrate it.

**Comment by falcon-git** [comment]
Yes, you're right. The H5P Content Types, H5P Core and H5P Editor shall always be platform independent, but we need to establish a contract of some sort so that the Moodle and other platform specific plugins may replace or extend the default video widget, and I guess the same goes for images and audio as well?

**Comment by nadavkav** [comment]
I agree. some kind of standardized hooks, maybe?

**Comment by thomasmars** [comment]
This is already possible. You can point both Interactive Video and Video to a direct link as long as it is publicly available on your web server through an URL.
For instance if you are setting a video inside Interactive Video you have the choice to upload a file or give a YouTube or direct video URL. Paste in the direct video URL inside the input field, for instance "https://www.html5rocks.com/en/tutorials/track/basics/treeOfLife/video/developerStories-en.webm" and  save the H5P and you will be able to use your video in the H5P without changing the maximum upload limit of your server.

Regarding integration with Moodle's repository api there is no news on this. It is an important issue, but does not currently have priority.

**Comment by thomasmars** [comment]
This needs to be implemented in core first, so that the Moodle plugin can implement an optional integration with it, so closing this for now.

**Comment by nadavkav** [comment]
Not sure why this was closed.
Moodle has already implemented in core the web-service (API) for getting a list of files a user can reuser (core_file\core_files_get_files) https://docs.moodle.org/dev/Web_service_API_functions
All is need from the H5P file picker UI is to display a list of those files and generate a proper URL when a file was selected. (similar to Moodle's internal file picker dialog)

**Comment by thomasmars** [comment]
Trying to close some old issues that are not currently being worked on. 
What I meant was that H5P Core needs to implement support for using custom integrations for retrieving media from other sources in order for the H5P Moodle plugin to support this, hence why I'm closing this for now. The references are good to keep here for when this functionality will be supported by core and this issue can be re-opened.

**Comment by edgecity13** [comment]
Hello Nadav, do you know if anyone is working on this project? We are very interested in using Moodle repositories to pick files for h5p interactive video and audio activities, and may be able to fund the project.

**Comment by nadavkav** [comment]
Now that Moodle adopted H5P in its core, I moved this issue to their
official Tracker:
https://tracker.moodle.org/browse/MDL-69258
