### ISSUE TITLE
Add RTL support + styles

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-moodle-plugin#86]
It would be very useful to have the Moodle user's [current language](https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L6608) available to the IFRAME (or DIV) of the hvp content. and use that parameter (flag?) to enable various RTL features: 
- UI translation (PHP & JS))
- Editor RTL alignment (+ Directionality RTL & LTR buttons + Initial editor directionality & alignment setup)
- Content styles

**Comment by nadavkav** [comment]
Applying the following suggested patch to h5p-php-library
https://github.com/h5p/h5p-php-library/pull/23

Enabled me to upload a new H5P.multichoice content package with patched RTL CSS selectors, which gave initial RTL support.
https://github.com/nadavkav/h5p-multi-choice/commit/053120ef868c1b8a4e8a34c649d9d2bfacb3c7b6

**Comment by falcon-git** [comment]
Reviewing this has been scheduled for next release. (Not the one we're working on now, but the one after this one. probably starts working on it in August)

**Comment by nadavkav** [comment]
Ok
Just know that I am basing css fixes in ALL h5p content components (those from the library) on the above fix. (that adds an rtl class, I can count on) so please see if I am on the right track with your future road map about implementing RTL/LTR support.

**Comment by nadavkav** [comment]
Hi @falcon-git , Any news on RTL support?

**Comment by fnoks** [comment]
@nadavkav : This issue is scheduled for the release we are working on, but won't promise you any release date.

I am not any expert in this field, but shouldn't we use the [dir](http://www.w3schools.com/tags/att_global_dir.asp) attribute instead of adding a class?

**Comment by nadavkav** [comment]
Thank you for considering it.
Moodle uses both, the dir attribute and a special classes dir-ltr / dir -rtl, to support cases where dir attribute is not enough. actually, dir-rtl is used a lot. 
So it is actually best if we use the dir attribute too.
And I will use the special dir-rtl only in cases where we have no other way of fixing the UI in RTL mode.

**Comment by nadavkav** [comment]
Though it would be very helpful to know what is going to be implemented, as I need to go through ALL the libraries and fix the interactions. (Locally, we fixes only a few we are currently using, but can not send PR as it is based on this fix)

**Comment by fnoks** [comment]
I have closed the related pull request. Just create a new one if you are able to implement the solution we have discussed!

**Comment by mkpelletier** [comment]
Greetings,
Has there been any progress in integrating this?  I am having issues working with RTL languages in the most recent H5P.  Furthermore, the absence of any style support is a problem.  These complex scripts work better with certain fonts, but the interactions editor does not seem to allow styling beyond what is available on the toolbar.  Is there a reason we cannot access the underlying html to style our text?

Thanks again for all your effort and a fantastic product!

**Comment by timothyylim** [comment]
Hi @mkpelletier, as far as I am aware, there hasn't been any progress integrating this just yet. It was a UX decision to not let authors access the underlying HTML. It reduces complexity and makes it easier to render the view as the possible inputs are limited in scope.

**Comment by thomasmars** [comment]
Closing this issue for the same reason as https://github.com/h5p/h5p-moodle-plugin/issues/81. Support for RTL languages must be implemented in H5P Core.

**Comment by nadavkav** [comment]
@thomasmars , Is there a relevant issue/ticket on the H5P jira that is related to fixing or supporting RTL in core H5P? (that you can link here)

**Comment by thomasmars** [comment]
@nadavkav Not to my knowledge, sorry. I have created a new issue (https://h5ptechnology.atlassian.net/browse/HFP-2825) that can be a central place for thoughts on how to approach RTL. Note that supporting RTL will be a huge endeavour, and is not likely to be fully supported any time soon. If we could find an incremental way to approach it, that might make it easier to support RTL eventually.

**Comment by nadavkav** [comment]
@thomasmars , I am not sure how much of a "huge endeavour" it should be, as I already have a forked version with RTL support:
https://github.com/iucc/h5p-moodle-plugin
Which is very much useable and being used in the Israeli academic sector for two years now.
Of course, it could be more elegant, but it works fine.
I have spread links to it here in the "issues" and on some forum discussions in the past, and I know other RTL communities use it too. so I suggest adopting some of the code into core. to make it easier for those who do not have the means to install it on their own.
