### ISSUE TITLE
LIMIT error on SQLserver instance

### ISSUE THREAD

**Issue by wullie** [h5p/h5p-moodle-plugin#93]
Hi,

I have installed h5p on our Moodle test server and get the following error when trying to add a h5p activity.

Incorrect syntax near 'LIMIT'.
SELECT id FROM mdl_hvp_libraries WHERE runnable = 1 LIMIT 1

We are using a SQLserver database which is not compatible with the LIMIT request. Could this please be looked at as I would really like to use this plugin?

Thanks

**Comment by icc** [comment]
Thank you for reporting the issue. I created a fix that should solve the issue. 
I would be greatful if you could test it on your SQLserver.
