### ISSUE TITLE
Grade results page shows students never enrolled in course

### ISSUE THREAD

**Issue by mikoleary** [h5p/h5p-moodle-plugin#94]
Created a test Activity module
List of results (~/mod/hvp/grade.php?id=XXXX) shows student never enrolled in course

**Comment by icc** [comment]
Yes, it appears there's no check for if the user belongs to the course or not, only if he has permission to view the task. So, for example, if someone who has permission to view all courses, like an admin, starts solving tasks they will get a grade as well.

I guess what you want is that only the score of those who're enrolled gets stored?

It worth noting that the current solution for grade.php just lists all of the grade_grades that belongs to the grade_item for the H5P. So it's more of a grade dump for all of the grades that belongs to the specifc activity.

This means that when you add new activities and Moodle automatically re-grades the activity, it will get 'empty' grades for those who have a grade in another activities. I.e. so all who already have a grade in the course will be added to the grade list of new activities.
(This is a bit different compared to how H5P results behave in other systems)

Thank you for reporting this issue, and feel free to share your thoughts or expectations as to how the grade report for H5P activities could be improved.

**Comment by icc** [comment]
One option if you don't want results from managers or teachers is to remove their permission to `mod/hvp:saveresults`, but that won't work for admins. Perhaps results from admins should always be ignored.
