### ISSUE TITLE
Blank screen when trying to add content

### ISSUE THREAD

**Issue by ChrisNZ2016** [h5p/h5p-moodle-plugin#96]
Running Moodle Moodle 3.1.1 (Build: 20160711) on Bitnami WAMP stack with Mahara also installed.

Installation goes fine, but when clicking add content and selecting H5P I end up at a blank white page (zero html).  I can access the plugins setttings screen so some of the plugin is working.

**Comment by icc** [comment]
Sounds like a PHP issue. Are you getting any error messages in your WAMP's error_log? If not you should try enabling debugging: https://docs.moodle.org/31/en/Debugging
