### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by mudrd8mz** [h5p/h5p-moodle-plugin#98]
It seems that the plugin does not pay much attention to CSRF protection - at least not via Moodle's inbuilt `sesskey()` mechanism. I noticed this at least for ajax.php actions, but sesskey is not used anywhere.

Am I missing something, such as H5P's custom protection mechanisms?

**Comment by icc** [comment]
H5P does have tokens set in session for each action which is checked as a security measure. This should be equal to Moodle's `sesskey()`, but we will of course double check this before releasing 1.0 and possible use `sesskey()` if necessary.
Thank you.

**Comment by icc** [comment]
This should be in place and double checked now.
