### ISSUE TITLE
Make use of thirdpartylibs.xml

### ISSUE THREAD

**Issue by mudrd8mz** [h5p/h5p-moodle-plugin#99]
See https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by icc** [comment]
Thank you, this will be fixed.

**Comment by thomasmars** [comment]
This should have been fixed in https://github.com/h5p/h5p-moodle-plugin/commit/7b828fe74ed51e23df3f3eed241f130662b28874
